/**
 * Financial-services taxonomy for search and matching.
 *
 * Pure configuration — no logic. Extend the term lists and rule tables below
 * to teach the classifier and ranker new financial-services vocabulary.
 *
 * Terms are matched case-insensitively on word boundaries. "strong" terms are
 * unambiguous for the sector (a single title hit is enough to classify);
 * "contextual" terms are suggestive but need at least one more hit somewhere
 * before they count (avoids tagging generic roles like "analyst" or "broker"
 * used outside financial services).
 */

export const FIN_SECTORS = [
  "insurance",
  "banking",
  "pensions",
  "asset_management",
  "accountancy_finance",
  "it_tech",
] as const;
export type FinSector = (typeof FIN_SECTORS)[number];

export const FIN_FUNCTIONS = [
  "underwriting",
  "claims",
  "broking",
  "actuarial",
  "compliance",
  "risk",
  "operations",
  "investments",
  "pensions_admin",
  "client_service",
  "finance",
  // IT/Tech functions
  "software_engineering",
  "cloud_infrastructure",
  "devops_sre",
  "data_engineering",
  "data_analytics",
  "data_science_ml_ai",
  "cyber_security",
  "it_operations_service",
  "end_user_support",
  "business_systems_analysis",
  "product_management_tech",
  "project_delivery_agile",
  "ux_design",
  "quality_assurance",
  "solutions_presales",
] as const;
export type FinFunction = (typeof FIN_FUNCTIONS)[number];

export const EMPLOYER_TYPES = [
  "insurer",
  "broker",
  "mga",
  "reinsurer",
  "bank",
  "pension_consultancy",
  "asset_manager",
  "wealth_manager",
] as const;
export type EmployerType = (typeof EMPLOYER_TYPES)[number];

export interface SectorTerms {
  strong: string[];
  contextual: string[];
}

export const SECTOR_TERMS: Record<FinSector, SectorTerms> = {
  insurance: {
    strong: [
      "underwriter",
      "underwriting",
      "bordereaux",
      "delegated authority",
      "binder",
      "lloyd's",
      "lloyds of london",
      "syndicate",
      "mga",
      "managing general agent",
      "reinsurance",
      "treaty",
      "facultative",
      "catastrophe modelling",
      "catastrophe modeling",
      "exposure management",
      "claims handler",
      "claims adjuster",
      "claims technician",
      "broking technician",
      "policy wordings",
      "insurer",
      "insurance",
      "actuary",
      "actuarial",
      "reserving",
      "pricing actuary",
    ],
    contextual: [
      "claims",
      "broker",
      "broking",
      "account handler",
      "wordings",
      "premium",
      "cover holder",
      "coverholder",
    ],
  },
  banking: {
    strong: [
      "kyc",
      "know your customer",
      "aml",
      "anti money laundering",
      "sanctions screening",
      "bank",
      "banking",
      "treasury",
      "liquidity risk",
      "alm",
      "asset liability management",
      "credit risk",
      "market risk",
      "operational risk",
      "front office",
      "middle office",
      "back office",
    ],
    contextual: [
      "onboarding",
      "sanctions",
      "payments",
      "financial crime",
      "capital markets",
      "trading desk",
      // Shared operations vocabulary (also common in asset management) —
      // needs corroboration before it can tag a job as banking.
      "settlements",
      "reconciliations",
      "custody",
    ],
  },
  pensions: {
    strong: [
      "pensions administrator",
      "pension administrator",
      "pensions administration",
      "pensions consultant",
      "pension scheme",
      "sipp",
      "ssas",
      "defined benefit",
      "defined contribution",
      "db pension",
      "dc pension",
      "trustee",
      "scheme events",
      "auto enrolment",
      "auto enrollment",
    ],
    contextual: [
      "pensions",
      "pension",
      "employee benefits",
      "governance",
      "implementation consultant",
      "final salary",
    ],
  },
  asset_management: {
    strong: [
      "fund accountant",
      "fund accounting",
      "fund controller",
      "investment operations",
      "fund operations",
      "transfer agency",
      "portfolio analyst",
      "performance analyst",
      "investment risk",
      "asset management",
      "asset manager",
      "fund manager",
      "portfolio manager",
      "client reporting",
      "esg analyst",
      "dealing desk",
      "nav",
    ],
    contextual: [
      "fund",
      "funds",
      "investments",
      "investment",
      "rfp",
      "product specialist",
      "dealing",
      "esg",
      "wealth management",
    ],
  },
  accountancy_finance: {
    strong: [
      "accountancy practice",
      "chartered accountant",
      "bookkeeper",
      "bookkeeping",
      "payroll",
      "financial accountant",
      "management accountant",
      "fp&a",
      "financial planning and analysis",
      "accounts payable",
      "accounts receivable",
      "credit controller",
      "audit senior",
      "tax manager",
      "tax consultant",
      "vat",
      "transfer pricing",
      "statutory accounts",
      "forensic accountant",
      "finance business partner",
    ],
    contextual: [
      "accountant",
      "audit",
      "tax",
      "billing",
      "ledger",
      "month end",
      "year end",
      "acca",
      "cima",
    ],
  },
  it_tech: {
    strong: [
      "software engineer",
      "software developer",
      "software development",
      "full stack",
      "front end developer",
      "frontend developer",
      "front end engineer",
      "frontend engineer",
      "backend developer",
      "backend engineer",
      "web developer",
      "mobile developer",
      "ios developer",
      "android developer",
      "devops",
      "site reliability engineer",
      "platform engineer",
      "cloud engineer",
      "cloud architect",
      "cloud infrastructure",
      "cyber security",
      "cybersecurity",
      "information security",
      "infosec",
      "penetration tester",
      "soc analyst",
      "data engineer",
      "data scientist",
      "machine learning",
      "systems administrator",
      "sysadmin",
      "network engineer",
      "help desk",
      "service desk",
      "it support",
      "it manager",
      "it director",
      "scrum master",
      "ux designer",
      "ui designer",
      "qa engineer",
      "test automation",
      "software tester",
      "salesforce",
      "sap consultant",
      "chief information officer",
      "chief technology officer",
      "database administrator",
    ],
    contextual: [
      "agile",
      "sprint",
      "saas",
      "api",
      "kubernetes",
      "docker",
      "aws",
      "azure",
      "gcp",
      "linux",
      "python",
      "java",
      "javascript",
      "typescript",
      "sql",
      "ci cd",
      "cloud",
      "infrastructure",
      "digital transformation",
    ],
  },
};

/**
 * Function classification terms. First hit in the title wins over hits in
 * weaker fields; order within each list does not matter.
 */
export const FUNCTION_TERMS: Record<FinFunction, string[]> = {
  underwriting: [
    "underwriter",
    "underwriting",
    "assistant underwriter",
    "trading underwriter",
    "binder",
    "delegated authority",
    "bordereaux",
  ],
  claims: [
    "claims handler",
    "claims adjuster",
    "claims technician",
    "claims examiner",
    "claims",
    "loss adjuster",
  ],
  broking: [
    "broker",
    "broking",
    "broking technician",
    "account handler",
    "account executive",
    "placement",
  ],
  actuarial: [
    "actuary",
    "actuarial",
    "pricing actuary",
    "reserving actuary",
    "reserving",
    "catastrophe modelling",
    "catastrophe modeling",
    "exposure management",
  ],
  compliance: [
    "compliance",
    "kyc",
    "know your customer",
    "aml",
    "anti money laundering",
    "sanctions",
    "financial crime",
    "onboarding",
    "regulatory",
  ],
  risk: [
    "credit risk",
    "market risk",
    "operational risk",
    "liquidity risk",
    "investment risk",
    "risk analyst",
    "risk manager",
    "risk officer",
  ],
  operations: [
    "operations",
    "settlements",
    "reconciliations",
    "custody",
    "middle office",
    "back office",
    "transfer agency",
    "dealing",
    "scheme events",
    "investment operations",
    "fund operations",
  ],
  investments: [
    "portfolio manager",
    "fund manager",
    "investment manager",
    "portfolio analyst",
    "investment analyst",
    "esg analyst",
    "performance analyst",
    "treasury",
  ],
  pensions_admin: [
    "pensions administrator",
    "pension administrator",
    "pensions administration",
    "pensions admin",
    "sipp administrator",
    "ssas administrator",
  ],
  client_service: [
    "client reporting",
    "client service",
    "client services",
    "rfp",
    "product specialist",
    "relationship manager",
    "client onboarding",
  ],
  finance: [
    "fund accountant",
    "fund accounting",
    "fund controller",
    "financial accountant",
    "finance",
    "financial reporting",
  ],
  software_engineering: [
    "software engineer",
    "software developer",
    "full stack",
    "backend",
    "front end",
    "frontend",
    "web developer",
    "mobile developer",
    "ios developer",
    "android developer",
    "software architect",
    "solution architect",
    "enterprise architect",
    "technical lead",
    "tech lead",
    "engineering manager",
    "engineering lead",
    "platform engineer",
    "embedded",
    "firmware",
    "game developer",
    "game programmer",
    "graphics engineer",
    "application developer",
  ],
  cloud_infrastructure: [
    "cloud engineer",
    "cloud architect",
    "cloud infrastructure",
    "cloud platform",
    "cloud operations",
    "systems administrator",
    "sysadmin",
    "server administrator",
    "virtualization",
    "vmware",
    "citrix",
    "network engineer",
    "network architect",
    "network administrator",
    "noc engineer",
    "telecoms",
    "telecommunications engineer",
    "infrastructure engineer",
    "voice engineer",
  ],
  devops_sre: [
    "devops",
    "site reliability",
    "sre",
    "build engineer",
    "release engineer",
    "ci cd",
    "configuration engineer",
    "platform reliability",
    "automation engineer",
  ],
  data_engineering: [
    "data engineer",
    "etl",
    "data pipeline",
    "data warehouse",
    "big data",
    "analytics engineer",
    "bi engineer",
    "database administrator",
    "dba",
    "database engineer",
    "database architect",
    "data steward",
    "data quality",
  ],
  data_analytics: [
    "data analyst",
    "business intelligence",
    "bi analyst",
    "reporting analyst",
    "mi analyst",
    "insight analyst",
  ],
  data_science_ml_ai: [
    "data scientist",
    "machine learning",
    "ml engineer",
    "ai engineer",
    "nlp",
    "computer vision",
    "deep learning",
    "algorithm engineer",
    "research scientist",
  ],
  cyber_security: [
    "cyber security",
    "cybersecurity",
    "information security",
    "infosec",
    "security engineer",
    "security analyst",
    "security architect",
    "penetration tester",
    "ethical hacker",
    "soc analyst",
    "soc engineer",
    "incident response",
    "threat intelligence",
    "application security",
    "red team",
    "blue team",
    "information assurance",
    "security operations",
  ],
  it_operations_service: [
    "it manager",
    "it operations",
    "it director",
    "service delivery",
    "chief information officer",
    "chief technology officer",
    "technology director",
    "it coordinator",
    "it analyst",
    "it specialist",
    "it trainer",
    "technical writer",
    "technical author",
    "it business partner",
  ],
  end_user_support: [
    "help desk",
    "service desk",
    "desktop support",
    "it support",
    "technical support",
    "field service engineer",
    "field support",
    "application support",
    "production support",
  ],
  business_systems_analysis: [
    "systems analyst",
    "business systems analyst",
    "technical business analyst",
    "it business analyst",
    "digital business analyst",
    "erp consultant",
    "sap consultant",
    "crm consultant",
    "salesforce administrator",
    "dynamics 365",
    "system designer",
  ],
  product_management_tech: [
    "product manager",
    "product owner",
    "chief product officer",
  ],
  project_delivery_agile: [
    "scrum master",
    "delivery manager",
    "agile",
    "release manager",
    "implementation manager",
    "digital project manager",
    "technology project manager",
    "software project manager",
    "it project manager",
    "programme manager",
  ],
  ux_design: [
    "ux designer",
    "ui designer",
    "product designer",
    "interaction designer",
    "ux researcher",
    "user experience",
    "user interface",
    "service designer",
    "visual designer",
    "experience designer",
    "design researcher",
  ],
  quality_assurance: [
    "qa engineer",
    "qa analyst",
    "test engineer",
    "software tester",
    "test automation",
    "automation test",
    "sdet",
    "test lead",
    "test manager",
    "quality assurance",
  ],
  solutions_presales: [
    "pre sales",
    "presales",
    "sales engineer",
    "solutions engineer",
    "solution consultant",
    "customer success engineer",
    "integration engineer",
    "professional services consultant",
    "implementation engineer",
  ],
};

/** Which sectors each function most plausibly belongs to (used as a tiebreak). */
export const FUNCTION_SECTOR_AFFINITY: Partial<Record<FinFunction, FinSector[]>> = {
  underwriting: ["insurance"],
  claims: ["insurance"],
  broking: ["insurance"],
  actuarial: ["insurance", "pensions"],
  pensions_admin: ["pensions"],
  investments: ["asset_management", "banking"],
  software_engineering: ["it_tech"],
  cloud_infrastructure: ["it_tech"],
  devops_sre: ["it_tech"],
  data_engineering: ["it_tech"],
  data_analytics: ["it_tech"],
  data_science_ml_ai: ["it_tech"],
  cyber_security: ["it_tech"],
  it_operations_service: ["it_tech"],
  end_user_support: ["it_tech"],
  business_systems_analysis: ["it_tech"],
  product_management_tech: ["it_tech"],
  project_delivery_agile: ["it_tech"],
  ux_design: ["it_tech"],
  quality_assurance: ["it_tech"],
  solutions_presales: ["it_tech"],
};

export interface EmployerTypeRule {
  type: EmployerType;
  /** Case-insensitive substrings matched against the company name. */
  nameKeywords: string[];
}

/**
 * Rule-based employer classification, evaluated top to bottom — first match
 * wins, so more specific rules (mga, reinsurer) come before generic ones.
 */
export const EMPLOYER_TYPE_RULES: EmployerTypeRule[] = [
  { type: "reinsurer", nameKeywords: ["reinsurance", " re ", "swiss re", "munich re", "hannover re", "scor"] },
  { type: "mga", nameKeywords: ["mga", "managing general", "underwriting agency", "coverholder"] },
  {
    type: "broker",
    nameKeywords: ["broker", "broking", "marsh", "aon", "willis towers watson", "wtw", "gallagher", "howden", "lockton", "miller insurance", "bms group"],
  },
  {
    type: "insurer",
    nameKeywords: ["insurance", "insurer", "assurance", "underwriters", "syndicate", "aviva", "axa", "allianz", "zurich", "hiscox", "beazley", "chubb", "rsa", "direct line", "admiral group", "lv=", "aig", "qbe", "markel", "lancashire", "brit ", "atrium", "canopius", "tokio marine"],
  },
  {
    type: "pension_consultancy",
    nameKeywords: ["pension", "pensions", "xps", "barnett waddingham", "hymans robertson", "lcp", "lane clark", "isio", "broadstone", "first actuarial", "mercer", "buck ", "gallagher benefit"],
  },
  {
    type: "wealth_manager",
    nameKeywords: ["wealth", "st. james's place", "st james's place", "rathbones", "brewin dolphin", "evelyn partners", "quilter", "charles stanley", "tilney"],
  },
  {
    type: "asset_manager",
    nameKeywords: ["asset management", "investment management", "investments", "fund managers", "capital partners", "blackrock", "schroders", "abrdn", "fidelity", "vanguard", "m&g", "legal & general investment", "lgim", "baillie gifford", "janus henderson", "jupiter", "invesco", "state street", "northern trust", "bny mellon", "amundi", "t. rowe price", "man group"],
  },
  {
    type: "bank",
    nameKeywords: ["bank", "banking", "hsbc", "barclays", "natwest", "lloyds", "santander", "monzo", "starling", "revolut", "goldman sachs", "jpmorgan", "j.p. morgan", "morgan stanley", "citi", "ubs", "deutsche", "bnp paribas", "societe generale", "credit suisse", "standard chartered", "nationwide"],
  },
];

/** Sector each employer type belongs to (for sector alignment boosts). */
export const EMPLOYER_TYPE_SECTOR: Record<EmployerType, FinSector> = {
  insurer: "insurance",
  broker: "insurance",
  mga: "insurance",
  reinsurer: "insurance",
  bank: "banking",
  pension_consultancy: "pensions",
  asset_manager: "asset_management",
  wealth_manager: "asset_management",
};
