// AUTO-GENERATED from src/config/data/careers-directory-seed.json
// by scripts/src/generateCareersDirectorySeed.ts — DO NOT hand-edit.
// To update: edit the seed JSON, then run
//   pnpm --filter @workspace/scripts run generate:careers-directory
//
// Data-only config: no business logic. Routing (ATS vs generic careers-page
// scraping, careers→board resolution) lives in lib/directory/engine.ts.

export type SeedIndustryKey =
  | "banking"
  | "pensions"
  | "asset_management"
  | "accountancy_finance"
  | "it_tech";

export interface SeedDirectoryEmployer {
  name: string;
  careersUrl: string;
  segment: string;
  platformHint:
    | "lever"
    | "ashby"
    | "workable"
    | "smartrecruiters"
    | "recruitee"
    | "teamtailor"
    | "workday"
    | "greenhouse"
    | "icims"
    | "careers_page";
  sectorTag: SeedIndustryKey;
  locationIncludes?: string[];
  notes?: string;
}

export interface SeedIndustryDirectory {
  label: string;
  segments: string[];
  employers: SeedDirectoryEmployer[];
}

export const CAREERS_DIRECTORY_SEED: Record<SeedIndustryKey, SeedIndustryDirectory> = {
  banking: {
    label: "Banking & Lending",
    segments: ["retail_bank","challenger_bank","commercial_lender","investment_bank","international_bank","central_bank"],
    employers: [
    {
      name: "Barclays",
      careersUrl: "https://search.jobs.barclays",
      segment: "retail_bank",
      platformHint: "careers_page",
      sectorTag: "banking",
    },
    {
      name: "HSBC",
      careersUrl: "https://mycareer.hsbc.com/en_GB/external",
      segment: "retail_bank",
      platformHint: "careers_page",
      sectorTag: "banking",
    },
    {
      name: "Lloyds Banking Group",
      careersUrl: "https://www.lloydsbankinggrouptalent.com",
      segment: "retail_bank",
      platformHint: "careers_page",
      sectorTag: "banking",
    },
    {
      name: "NatWest Group",
      careersUrl: "https://jobs.natwestgroup.com",
      segment: "retail_bank",
      platformHint: "careers_page",
      sectorTag: "banking",
    },
    {
      name: "Santander UK",
      careersUrl: "https://www.santanderjobs.co.uk",
      segment: "retail_bank",
      platformHint: "careers_page",
      sectorTag: "banking",
    },
    {
      name: "Standard Chartered",
      careersUrl: "https://jobs.standardchartered.com",
      segment: "retail_bank",
      platformHint: "careers_page",
      sectorTag: "banking",
    },
    {
      name: "Virgin Money",
      careersUrl: "https://careers.virginmoney.com",
      segment: "retail_bank",
      platformHint: "careers_page",
      sectorTag: "banking",
    },
    {
      name: "Metro Bank",
      careersUrl: "https://careers.metrobankonline.co.uk",
      segment: "challenger_bank",
      platformHint: "careers_page",
      sectorTag: "banking",
    },
    {
      name: "Monzo",
      careersUrl: "https://boards.greenhouse.io/monzo",
      segment: "challenger_bank",
      platformHint: "greenhouse",
      sectorTag: "banking",
      locationIncludes: ["london","united kingdom","uk","remote"],
    },
    {
      name: "Starling Bank",
      careersUrl: "https://apply.workable.com/starling-bank/",
      segment: "challenger_bank",
      platformHint: "workable",
      sectorTag: "banking",
    },
    {
      name: "Revolut",
      careersUrl: "https://www.revolut.com/careers/",
      segment: "challenger_bank",
      platformHint: "careers_page",
      sectorTag: "banking",
      notes: "No public ATS board found (probed greenhouse/lever/ashby/workable/smartrecruiters); own JS-heavy careers portal — needs Firecrawl",
    },
    {
      name: "Zopa",
      careersUrl: "https://jobs.lever.co/zopa",
      segment: "challenger_bank",
      platformHint: "lever",
      sectorTag: "banking",
    },
    {
      name: "Atom Bank",
      careersUrl: "https://www.atombank.co.uk/careers/",
      segment: "challenger_bank",
      platformHint: "careers_page",
      sectorTag: "banking",
    },
    {
      name: "Allica Bank",
      careersUrl: "https://www.allica.bank/careers",
      segment: "challenger_bank",
      platformHint: "careers_page",
      sectorTag: "banking",
    },
    {
      name: "ClearBank",
      careersUrl: "https://jobs.ashbyhq.com/clearbank",
      segment: "challenger_bank",
      platformHint: "ashby",
      sectorTag: "banking",
    },
    {
      name: "OakNorth",
      careersUrl: "https://jobs.ashbyhq.com/oaknorth",
      segment: "commercial_lender",
      platformHint: "ashby",
      sectorTag: "banking",
      locationIncludes: ["london","manchester","united kingdom","uk"],
      notes: "Ashby board token oaknorth (probed July 2026); board is global (NY/Gurugram) so UK locationIncludes applied",
    },
    {
      name: "Shawbrook Bank",
      careersUrl: "https://www.shawbrook.co.uk/careers/",
      segment: "commercial_lender",
      platformHint: "careers_page",
      sectorTag: "banking",
    },
    {
      name: "Tandem Bank",
      careersUrl: "https://www.tandem.co.uk/careers",
      segment: "challenger_bank",
      platformHint: "careers_page",
      sectorTag: "banking",
    },
    {
      name: "JPMorgan",
      careersUrl: "https://careers.jpmorgan.com",
      segment: "investment_bank",
      platformHint: "careers_page",
      sectorTag: "banking",
    },
    {
      name: "Bank of America",
      careersUrl: "https://careers.bankofamerica.com",
      segment: "investment_bank",
      platformHint: "careers_page",
      sectorTag: "banking",
    },
    {
      name: "Citi",
      careersUrl: "https://jobs.citi.com",
      segment: "investment_bank",
      platformHint: "careers_page",
      sectorTag: "banking",
    },
    {
      name: "Goldman Sachs",
      careersUrl: "https://www.goldmansachs.com/careers",
      segment: "investment_bank",
      platformHint: "careers_page",
      sectorTag: "banking",
    },
    {
      name: "Morgan Stanley",
      careersUrl: "https://www.morganstanley.com/careers",
      segment: "investment_bank",
      platformHint: "careers_page",
      sectorTag: "banking",
    },
    {
      name: "UBS",
      careersUrl: "https://jobs.ubs.com/TGnewUI/Search/home/HomeWithPreLoad?partnerid=25008&siteid=5012&PageType=searchResults",
      segment: "investment_bank",
      platformHint: "careers_page",
      sectorTag: "banking",
      notes: "Official careers hub www.ubs.com blocks non-browser fetches; this is the ATS search entry",
    },
    {
      name: "Deutsche Bank",
      careersUrl: "https://careers.db.com",
      segment: "investment_bank",
      platformHint: "careers_page",
      sectorTag: "banking",
    },
    {
      name: "RBC Capital Markets",
      careersUrl: "https://jobs.rbc.com",
      segment: "investment_bank",
      platformHint: "careers_page",
      sectorTag: "banking",
    },
    {
      name: "Wells Fargo",
      careersUrl: "https://www.wellsfargojobs.com",
      segment: "international_bank",
      platformHint: "careers_page",
      sectorTag: "banking",
    },
    {
      name: "BNP Paribas UK",
      careersUrl: "https://careers.bnpparibas.co.uk",
      segment: "international_bank",
      platformHint: "careers_page",
      sectorTag: "banking",
    },
    {
      name: "Crédit Agricole CIB",
      careersUrl: "https://jobs.ca-cib.com",
      segment: "international_bank",
      platformHint: "careers_page",
      sectorTag: "banking",
    },
    {
      name: "Société Générale",
      careersUrl: "https://careers.societegenerale.com",
      segment: "international_bank",
      platformHint: "careers_page",
      sectorTag: "banking",
    },
    {
      name: "ING",
      careersUrl: "https://www.ing.jobs",
      segment: "international_bank",
      platformHint: "careers_page",
      sectorTag: "banking",
    },
    {
      name: "MUFG EMEA",
      careersUrl: "https://mufgub.wd3.myworkdayjobs.com/MUFG-Careers",
      segment: "international_bank",
      platformHint: "workday",
      sectorTag: "banking",
    },
    {
      name: "SMBC Group EMEA",
      careersUrl: "https://www.smbcgroup.com/emea/careers",
      segment: "international_bank",
      platformHint: "careers_page",
      sectorTag: "banking",
    },
    {
      name: "Mizuho EMEA",
      careersUrl: "https://www.mizuhogroup.com/emea/careers",
      segment: "international_bank",
      platformHint: "careers_page",
      sectorTag: "banking",
    },
    {
      name: "Bank of England",
      careersUrl: "https://www.bankofengland.co.uk/careers",
      segment: "central_bank",
      platformHint: "careers_page",
      sectorTag: "banking",
    },
    {
      name: "Griffin",
      careersUrl: "https://jobs.ashbyhq.com/griffin",
      segment: "challenger_bank",
      platformHint: "ashby",
      sectorTag: "banking",
    },
    ],
  },
  pensions: {
    label: "Pensions & Retirement",
    segments: ["provider","administrator","consultancy"],
    employers: [
    {
      name: "Aviva",
      careersUrl: "https://careers.aviva.com",
      segment: "provider",
      platformHint: "careers_page",
      sectorTag: "pensions",
    },
    {
      name: "Legal & General",
      careersUrl: "https://careers.legalandgeneral.com",
      segment: "provider",
      platformHint: "careers_page",
      sectorTag: "pensions",
    },
    {
      name: "Royal London",
      careersUrl: "https://jobs.royallondon.com",
      segment: "provider",
      platformHint: "careers_page",
      sectorTag: "pensions",
    },
    {
      name: "Phoenix Group",
      careersUrl: "https://www.thephoenixgroup.com/careers",
      segment: "provider",
      platformHint: "careers_page",
      sectorTag: "pensions",
    },
    {
      name: "Aegon UK",
      careersUrl: "https://www.aegon.co.uk/careers",
      segment: "provider",
      platformHint: "careers_page",
      sectorTag: "pensions",
    },
    {
      name: "Smart Pension",
      careersUrl: "https://www.smartpension.co.uk/careers",
      segment: "provider",
      platformHint: "careers_page",
      sectorTag: "pensions",
    },
    {
      name: "The People's Partnership",
      careersUrl: "https://peoplespartnership.co.uk/careers/",
      segment: "provider",
      platformHint: "careers_page",
      sectorTag: "pensions",
    },
    {
      name: "XPS Pensions Group",
      careersUrl: "https://careers.xpsgroup.com",
      segment: "consultancy",
      platformHint: "careers_page",
      sectorTag: "pensions",
    },
    {
      name: "Barnett Waddingham",
      careersUrl: "https://www.barnett-waddingham.co.uk/careers/",
      segment: "consultancy",
      platformHint: "careers_page",
      sectorTag: "pensions",
    },
    {
      name: "Hymans Robertson",
      careersUrl: "https://careers.hymans.co.uk",
      segment: "consultancy",
      platformHint: "careers_page",
      sectorTag: "pensions",
    },
    {
      name: "LCP",
      careersUrl: "https://www.lcp.com/en/careers",
      segment: "consultancy",
      platformHint: "careers_page",
      sectorTag: "pensions",
    },
    {
      name: "WTW",
      careersUrl: "https://careers.wtwco.com",
      segment: "consultancy",
      platformHint: "careers_page",
      sectorTag: "pensions",
    },
    {
      name: "Marsh McLennan (Mercer)",
      careersUrl: "https://careers.marshmclennan.com",
      segment: "consultancy",
      platformHint: "careers_page",
      sectorTag: "pensions",
    },
    {
      name: "Isio",
      careersUrl: "https://www.isio.com/careers/",
      segment: "consultancy",
      platformHint: "careers_page",
      sectorTag: "pensions",
    },
    {
      name: "Broadstone",
      careersUrl: "https://broadstone.co.uk/careers/",
      segment: "consultancy",
      platformHint: "careers_page",
      sectorTag: "pensions",
    },
    {
      name: "Capita Pension Solutions",
      careersUrl: "https://www.capita.com/careers",
      segment: "administrator",
      platformHint: "careers_page",
      sectorTag: "pensions",
    },
    {
      name: "Canada Life UK",
      careersUrl: "https://www.canadalife.co.uk/our-company/careers/",
      segment: "provider",
      platformHint: "careers_page",
      sectorTag: "pensions",
    },
    {
      name: "Just Group",
      careersUrl: "https://www.justgroupplc.co.uk/careers",
      segment: "provider",
      platformHint: "careers_page",
      sectorTag: "pensions",
    },
    {
      name: "Aon",
      careersUrl: "https://jobs.aon.com",
      segment: "consultancy",
      platformHint: "careers_page",
      sectorTag: "pensions",
    },
    ],
  },
  asset_management: {
    label: "Asset & Wealth Management",
    segments: ["asset_manager","hedge_fund","private_markets","wealth_manager"],
    employers: [
    {
      name: "Schroders",
      careersUrl: "https://www.schroders.com/en/global/individual/about-us/careers/",
      segment: "asset_manager",
      platformHint: "careers_page",
      sectorTag: "asset_management",
    },
    {
      name: "abrdn",
      careersUrl: "https://careers.abrdn.com",
      segment: "asset_manager",
      platformHint: "careers_page",
      sectorTag: "asset_management",
    },
    {
      name: "M&G",
      careersUrl: "https://careers.mandg.com",
      segment: "asset_manager",
      platformHint: "careers_page",
      sectorTag: "asset_management",
    },
    {
      name: "Baillie Gifford",
      careersUrl: "https://careers.bailliegifford.com",
      segment: "asset_manager",
      platformHint: "careers_page",
      sectorTag: "asset_management",
    },
    {
      name: "Janus Henderson",
      careersUrl: "https://www.janushenderson.com/en-gb/careers/",
      segment: "asset_manager",
      platformHint: "careers_page",
      sectorTag: "asset_management",
    },
    {
      name: "Jupiter Asset Management",
      careersUrl: "https://www.jupiteram.com/careers/",
      segment: "asset_manager",
      platformHint: "careers_page",
      sectorTag: "asset_management",
    },
    {
      name: "Fidelity International",
      careersUrl: "https://careers.fidelityinternational.com",
      segment: "asset_manager",
      platformHint: "careers_page",
      sectorTag: "asset_management",
    },
    {
      name: "Man Group",
      careersUrl: "https://www.man.com/careers",
      segment: "hedge_fund",
      platformHint: "careers_page",
      sectorTag: "asset_management",
    },
    {
      name: "Marshall Wace",
      careersUrl: "https://www.mwam.com/careers/",
      segment: "hedge_fund",
      platformHint: "careers_page",
      sectorTag: "asset_management",
    },
    {
      name: "Brevan Howard",
      careersUrl: "https://www.brevanhoward.com/careers/",
      segment: "hedge_fund",
      platformHint: "careers_page",
      sectorTag: "asset_management",
    },
    {
      name: "Bridgepoint",
      careersUrl: "https://www.bridgepoint.eu/careers",
      segment: "private_markets",
      platformHint: "careers_page",
      sectorTag: "asset_management",
    },
    {
      name: "ICG",
      careersUrl: "https://www.icgam.com/careers/",
      segment: "private_markets",
      platformHint: "careers_page",
      sectorTag: "asset_management",
    },
    {
      name: "3i Group",
      careersUrl: "https://www.3i.com/careers/",
      segment: "private_markets",
      platformHint: "careers_page",
      sectorTag: "asset_management",
    },
    {
      name: "Rathbones",
      careersUrl: "https://www.rathbones.com/careers",
      segment: "wealth_manager",
      platformHint: "careers_page",
      sectorTag: "asset_management",
    },
    {
      name: "Evelyn Partners",
      careersUrl: "https://www.evelyn.com/careers/",
      segment: "wealth_manager",
      platformHint: "careers_page",
      sectorTag: "asset_management",
    },
    {
      name: "St. James's Place",
      careersUrl: "https://careers.sjp.co.uk",
      segment: "wealth_manager",
      platformHint: "careers_page",
      sectorTag: "asset_management",
    },
    {
      name: "BlackRock",
      careersUrl: "https://careers.blackrock.com",
      segment: "asset_manager",
      platformHint: "careers_page",
      sectorTag: "asset_management",
    },
    {
      name: "Vanguard",
      careersUrl: "https://www.vanguardjobs.com",
      segment: "asset_manager",
      platformHint: "careers_page",
      sectorTag: "asset_management",
    },
    {
      name: "PIMCO",
      careersUrl: "https://www.pimco.com/en-gb/careers",
      segment: "asset_manager",
      platformHint: "careers_page",
      sectorTag: "asset_management",
      notes: "Site blocks non-browser fetches (403); likely needs Firecrawl",
    },
    {
      name: "Franklin Templeton",
      careersUrl: "https://www.franklintempletoncareers.com",
      segment: "asset_manager",
      platformHint: "careers_page",
      sectorTag: "asset_management",
    },
    {
      name: "Invesco",
      careersUrl: "https://careers.invesco.com",
      segment: "asset_manager",
      platformHint: "careers_page",
      sectorTag: "asset_management",
    },
    {
      name: "State Street",
      careersUrl: "https://careers.statestreet.com",
      segment: "asset_manager",
      platformHint: "careers_page",
      sectorTag: "asset_management",
    },
    {
      name: "AQR Capital Management",
      careersUrl: "https://careers.aqr.com",
      segment: "hedge_fund",
      platformHint: "careers_page",
      sectorTag: "asset_management",
    },
    {
      name: "Brookfield",
      careersUrl: "https://www.brookfield.com/careers",
      segment: "private_markets",
      platformHint: "careers_page",
      sectorTag: "asset_management",
    },
    {
      name: "Blackstone",
      careersUrl: "https://www.blackstone.com/careers/",
      segment: "private_markets",
      platformHint: "careers_page",
      sectorTag: "asset_management",
    },
    ],
  },
  accountancy_finance: {
    label: "Accountancy & Finance",
    segments: ["big4","mid_tier","consultancy"],
    employers: [
    {
      name: "Deloitte UK",
      careersUrl: "https://www.deloitte.com/uk/en/careers.html",
      segment: "big4",
      platformHint: "careers_page",
      sectorTag: "accountancy_finance",
    },
    {
      name: "PwC UK",
      careersUrl: "https://www.pwc.co.uk/careers.html",
      segment: "big4",
      platformHint: "careers_page",
      sectorTag: "accountancy_finance",
    },
    {
      name: "KPMG UK",
      careersUrl: "https://www.kpmgcareers.co.uk",
      segment: "big4",
      platformHint: "careers_page",
      sectorTag: "accountancy_finance",
    },
    {
      name: "EY UK",
      careersUrl: "https://www.ey.com/en_uk/careers",
      segment: "big4",
      platformHint: "careers_page",
      sectorTag: "accountancy_finance",
    },
    {
      name: "BDO UK",
      careersUrl: "https://careers.bdo.co.uk",
      segment: "mid_tier",
      platformHint: "careers_page",
      sectorTag: "accountancy_finance",
    },
    {
      name: "Grant Thornton UK",
      careersUrl: "https://www.grantthornton.co.uk/careers/",
      segment: "mid_tier",
      platformHint: "careers_page",
      sectorTag: "accountancy_finance",
    },
    {
      name: "RSM UK",
      careersUrl: "https://www.rsmuk.com/careers",
      segment: "mid_tier",
      platformHint: "careers_page",
      sectorTag: "accountancy_finance",
    },
    {
      name: "Forvis Mazars",
      careersUrl: "https://www.forvismazars.com/uk/en/careers",
      segment: "mid_tier",
      platformHint: "careers_page",
      sectorTag: "accountancy_finance",
    },
    {
      name: "Crowe UK",
      careersUrl: "https://www.crowe.com/uk/careers",
      segment: "mid_tier",
      platformHint: "careers_page",
      sectorTag: "accountancy_finance",
    },
    {
      name: "Saffery",
      careersUrl: "https://www.saffery.com/careers/",
      segment: "mid_tier",
      platformHint: "careers_page",
      sectorTag: "accountancy_finance",
    },
    {
      name: "Moore Kingston Smith",
      careersUrl: "https://mks.co.uk/careers/",
      segment: "mid_tier",
      platformHint: "careers_page",
      sectorTag: "accountancy_finance",
    },
    {
      name: "Menzies",
      careersUrl: "https://www.menzies.co.uk/careers/",
      segment: "mid_tier",
      platformHint: "careers_page",
      sectorTag: "accountancy_finance",
    },
    {
      name: "Azets",
      careersUrl: "https://www.azets.co.uk/careers/",
      segment: "mid_tier",
      platformHint: "careers_page",
      sectorTag: "accountancy_finance",
    },
    {
      name: "Buzzacott",
      careersUrl: "https://www.buzzacott.co.uk/careers",
      segment: "mid_tier",
      platformHint: "careers_page",
      sectorTag: "accountancy_finance",
    },
    {
      name: "Price Bailey",
      careersUrl: "https://www.pricebailey.co.uk/careers/",
      segment: "mid_tier",
      platformHint: "careers_page",
      sectorTag: "accountancy_finance",
    },
    {
      name: "Bishop Fleming",
      careersUrl: "https://www.bishopfleming.co.uk/careers",
      segment: "mid_tier",
      platformHint: "careers_page",
      sectorTag: "accountancy_finance",
    },
    {
      name: "PKF Littlejohn",
      careersUrl: "https://www.pkf-l.com/careers/",
      segment: "mid_tier",
      platformHint: "careers_page",
      sectorTag: "accountancy_finance",
    },
    {
      name: "MHA",
      careersUrl: "https://careers.mha.co.uk",
      segment: "mid_tier",
      platformHint: "careers_page",
      sectorTag: "accountancy_finance",
    },
    ],
  },
  it_tech: {
    label: "IT & Technology",
    segments: ["fintech","software","consultancy"],
    employers: [
    {
      name: "Wise",
      careersUrl: "https://www.wise.jobs",
      segment: "fintech",
      platformHint: "careers_page",
      sectorTag: "it_tech",
      locationIncludes: ["london","united kingdom","uk"],
      notes: "wise.jobs crawls fine but is a global board with no structured locations; UK locationIncludes matches URL slugs like -in-london- (crawler-path filter)",
    },
    {
      name: "Checkout.com",
      careersUrl: "https://jobs.ashbyhq.com/checkout.com",
      segment: "fintech",
      platformHint: "ashby",
      sectorTag: "it_tech",
      locationIncludes: ["london","united kingdom","uk"],
    },
    {
      name: "GoCardless",
      careersUrl: "https://boards.greenhouse.io/gocardless",
      segment: "fintech",
      platformHint: "greenhouse",
      sectorTag: "it_tech",
      locationIncludes: ["london","united kingdom","uk","remote"],
    },
    {
      name: "Thought Machine",
      careersUrl: "https://jobs.ashbyhq.com/thought-machine",
      segment: "fintech",
      platformHint: "ashby",
      sectorTag: "it_tech",
      locationIncludes: ["london","united kingdom","uk"],
    },
    {
      name: "ClearScore",
      careersUrl: "https://www.clearscore.com/careers",
      segment: "fintech",
      platformHint: "careers_page",
      sectorTag: "it_tech",
      notes: "Workable account 'clearscore' resolves but widget returns 0 jobs; own careers site is JS-heavy — needs Firecrawl",
    },
    {
      name: "Tide",
      careersUrl: "https://boards.greenhouse.io/tide",
      segment: "fintech",
      platformHint: "greenhouse",
      sectorTag: "it_tech",
      locationIncludes: ["london","united kingdom","uk","remote"],
    },
    {
      name: "Zilch",
      careersUrl: "https://jobs.ashbyhq.com/zilch",
      segment: "fintech",
      platformHint: "ashby",
      sectorTag: "it_tech",
    },
    {
      name: "Multiverse",
      careersUrl: "https://jobs.ashbyhq.com/multiverse",
      segment: "software",
      platformHint: "ashby",
      sectorTag: "it_tech",
    },
    {
      name: "Octopus Energy Group",
      careersUrl: "https://jobs.lever.co/octoenergy",
      segment: "software",
      platformHint: "lever",
      sectorTag: "it_tech",
    },
    {
      name: "Snyk",
      careersUrl: "https://snyk.io/careers/",
      segment: "software",
      platformHint: "careers_page",
      sectorTag: "it_tech",
      notes: "No public ATS board found (probed greenhouse/lever/ashby/workable/smartrecruiters); own JS-heavy careers portal — needs Firecrawl",
    },
    {
      name: "Darktrace",
      careersUrl: "https://careers.darktrace.com",
      segment: "software",
      platformHint: "careers_page",
      sectorTag: "it_tech",
      notes: "No public ATS board found (probed greenhouse/lever/ashby/workable/smartrecruiters); own JS-heavy careers portal — needs Firecrawl",
    },
    {
      name: "Sage",
      careersUrl: "https://www.sage.com/en-gb/company/careers/",
      segment: "software",
      platformHint: "careers_page",
      sectorTag: "it_tech",
    },
    {
      name: "Kainos",
      careersUrl: "https://careers.kainos.com",
      segment: "consultancy",
      platformHint: "careers_page",
      sectorTag: "it_tech",
    },
    {
      name: "Endava",
      careersUrl: "https://careers.smartrecruiters.com/Endava",
      segment: "consultancy",
      platformHint: "smartrecruiters",
      sectorTag: "it_tech",
      locationIncludes: ["london","united kingdom","uk"],
      notes: "SmartRecruiters company Endava (234 global postings, probed July 2026); UK locationIncludes applied; own careers site is a static shell with no listings",
    },
    {
      name: "FDM Group",
      careersUrl: "https://www.fdmgroup.com/careers/",
      segment: "consultancy",
      platformHint: "careers_page",
      sectorTag: "it_tech",
    },
    {
      name: "Softcat",
      careersUrl: "https://www.softcat.com/careers",
      segment: "consultancy",
      platformHint: "careers_page",
      sectorTag: "it_tech",
    },
    {
      name: "Microsoft",
      careersUrl: "https://careers.microsoft.com",
      segment: "software",
      platformHint: "careers_page",
      sectorTag: "it_tech",
    },
    {
      name: "Google",
      careersUrl: "https://www.google.com/about/careers/applications/",
      segment: "software",
      platformHint: "careers_page",
      sectorTag: "it_tech",
    },
    {
      name: "Amazon",
      careersUrl: "https://www.amazon.jobs",
      segment: "software",
      platformHint: "careers_page",
      sectorTag: "it_tech",
    },
    {
      name: "Meta",
      careersUrl: "https://www.metacareers.com",
      segment: "software",
      platformHint: "careers_page",
      sectorTag: "it_tech",
      notes: "Site blocks non-browser fetches (400); likely needs Firecrawl",
    },
    {
      name: "Apple",
      careersUrl: "https://jobs.apple.com",
      segment: "software",
      platformHint: "careers_page",
      sectorTag: "it_tech",
    },
    {
      name: "Oracle",
      careersUrl: "https://careers.oracle.com",
      segment: "software",
      platformHint: "careers_page",
      sectorTag: "it_tech",
    },
    {
      name: "Salesforce",
      careersUrl: "https://careers.salesforce.com",
      segment: "software",
      platformHint: "careers_page",
      sectorTag: "it_tech",
    },
    {
      name: "SAP",
      careersUrl: "https://jobs.sap.com",
      segment: "software",
      platformHint: "careers_page",
      sectorTag: "it_tech",
    },
    {
      name: "Adobe",
      careersUrl: "https://careers.adobe.com",
      segment: "software",
      platformHint: "careers_page",
      sectorTag: "it_tech",
    },
    {
      name: "ServiceNow",
      careersUrl: "https://careers.servicenow.com",
      segment: "software",
      platformHint: "careers_page",
      sectorTag: "it_tech",
    },
    {
      name: "Workday",
      careersUrl: "https://workday.wd5.myworkdayjobs.com/Workday",
      segment: "software",
      platformHint: "workday",
      sectorTag: "it_tech",
    },
    {
      name: "Snowflake",
      careersUrl: "https://careers.snowflake.com",
      segment: "software",
      platformHint: "careers_page",
      sectorTag: "it_tech",
    },
    {
      name: "HubSpot",
      careersUrl: "https://www.hubspot.com/careers",
      segment: "software",
      platformHint: "careers_page",
      sectorTag: "it_tech",
    },
    {
      name: "IBM",
      careersUrl: "https://www.ibm.com/careers",
      segment: "consultancy",
      platformHint: "careers_page",
      sectorTag: "it_tech",
    },
    {
      name: "Accenture",
      careersUrl: "https://www.accenture.com/gb-en/careers",
      segment: "consultancy",
      platformHint: "careers_page",
      sectorTag: "it_tech",
      locationIncludes: ["london","united kingdom","uk"],
      notes: "Careers page resolves to global Workday board (wd103) whose listing payload has no locationsText, so the UK filter drops everything — better than ingesting global no-location noise; needs a UK-facet-aware fetch or Firecrawl",
    },
    {
      name: "Capgemini",
      careersUrl: "https://www.capgemini.com/gb-en/careers/",
      segment: "consultancy",
      platformHint: "careers_page",
      sectorTag: "it_tech",
    },
    {
      name: "Cognizant",
      careersUrl: "https://careers.cognizant.com",
      segment: "consultancy",
      platformHint: "careers_page",
      sectorTag: "it_tech",
    },
    {
      name: "Infosys",
      careersUrl: "https://www.infosys.com/careers/",
      segment: "consultancy",
      platformHint: "careers_page",
      sectorTag: "it_tech",
      notes: "Site blocks non-browser fetches (403); likely needs Firecrawl",
    },
    {
      name: "TCS",
      careersUrl: "https://www.tcs.com/careers",
      segment: "consultancy",
      platformHint: "careers_page",
      sectorTag: "it_tech",
      notes: "Site blocks non-browser fetches (403); likely needs Firecrawl",
    },
    {
      name: "Wipro",
      careersUrl: "https://careers.wipro.com",
      segment: "consultancy",
      platformHint: "careers_page",
      sectorTag: "it_tech",
    },
    {
      name: "SumUp",
      careersUrl: "https://boards.greenhouse.io/sumup",
      segment: "fintech",
      platformHint: "greenhouse",
      sectorTag: "it_tech",
      locationIncludes: ["london","united kingdom","uk","remote"],
    },
    {
      name: "Dojo",
      careersUrl: "https://boards.greenhouse.io/dojo",
      segment: "fintech",
      platformHint: "greenhouse",
      sectorTag: "it_tech",
      locationIncludes: ["london","united kingdom","uk"],
    },
    {
      name: "Marshmallow",
      careersUrl: "https://jobs.ashbyhq.com/marshmallow",
      segment: "fintech",
      platformHint: "ashby",
      sectorTag: "it_tech",
    },
    {
      name: "Twilio",
      careersUrl: "https://boards.greenhouse.io/twilio",
      segment: "software",
      platformHint: "greenhouse",
      sectorTag: "it_tech",
      locationIncludes: ["london","united kingdom","uk","remote"],
    },
    {
      name: "Elastic",
      careersUrl: "https://boards.greenhouse.io/elastic",
      segment: "software",
      platformHint: "greenhouse",
      sectorTag: "it_tech",
      locationIncludes: ["london","united kingdom","uk","remote","emea"],
    },
    {
      name: "GitLab",
      careersUrl: "https://boards.greenhouse.io/gitlab",
      segment: "software",
      platformHint: "greenhouse",
      sectorTag: "it_tech",
      locationIncludes: ["london","united kingdom","uk","remote","emea"],
    },
    {
      name: "Skyscanner",
      careersUrl: "https://boards.greenhouse.io/skyscanner",
      segment: "software",
      platformHint: "greenhouse",
      sectorTag: "it_tech",
      locationIncludes: ["london","united kingdom","uk","edinburgh","glasgow","barcelona"],
    },
    {
      name: "Trustpilot",
      careersUrl: "https://boards.greenhouse.io/trustpilot",
      segment: "software",
      platformHint: "greenhouse",
      sectorTag: "it_tech",
      locationIncludes: ["london","united kingdom","uk","edinburgh"],
    },
    {
      name: "Canonical",
      careersUrl: "https://boards.greenhouse.io/canonical",
      segment: "software",
      platformHint: "greenhouse",
      sectorTag: "it_tech",
      locationIncludes: ["london","united kingdom","uk","remote","emea"],
    },
    {
      name: "Databricks",
      careersUrl: "https://boards.greenhouse.io/databricks",
      segment: "software",
      platformHint: "greenhouse",
      sectorTag: "it_tech",
      locationIncludes: ["london","united kingdom","uk"],
    },
    {
      name: "Cloudflare",
      careersUrl: "https://boards.greenhouse.io/cloudflare",
      segment: "software",
      platformHint: "greenhouse",
      sectorTag: "it_tech",
      locationIncludes: ["london","united kingdom","uk"],
      notes: "Greenhouse board hides city names (locations are Hybrid/Distributed), so the UK location filter yields 0 jobs; needs an alternative source or offices-based filtering",
    },
    {
      name: "Datadog",
      careersUrl: "https://boards.greenhouse.io/datadog",
      segment: "software",
      platformHint: "greenhouse",
      sectorTag: "it_tech",
      locationIncludes: ["london","united kingdom","uk"],
    },
    {
      name: "Palantir",
      careersUrl: "https://jobs.lever.co/palantir",
      segment: "software",
      platformHint: "lever",
      sectorTag: "it_tech",
      locationIncludes: ["london","united kingdom","uk"],
    },
    {
      name: "Deliveroo",
      careersUrl: "https://jobs.ashbyhq.com/deliveroo",
      segment: "software",
      platformHint: "ashby",
      sectorTag: "it_tech",
      locationIncludes: ["london","united kingdom","uk"],
    },
    {
      name: "Improbable",
      careersUrl: "https://jobs.ashbyhq.com/improbable",
      segment: "software",
      platformHint: "ashby",
      sectorTag: "it_tech",
    },
    {
      name: "Moonpig",
      careersUrl: "https://jobs.lever.co/moonpig",
      segment: "software",
      platformHint: "lever",
      sectorTag: "it_tech",
      locationIncludes: ["london","united kingdom","uk"],
    },
    ],
  },
};

/** Seed rows that could not be included (e.g. no careers URL). */
export const CAREERS_DIRECTORY_SEED_UNRESOLVED: Array<{
  name: string;
  industry: string;
  segment: string;
  reason: string;
}> = [

];
