// AUTO-GENERATED from src/config/data/London-Insurance-Market-Directory.md
// by scripts/src/generateLondonInsuranceEmployers.ts — DO NOT hand-edit.
// To update: edit the directory md, then run
//   pnpm --filter @workspace/scripts run generate:london-directory
//
// Data-only config: no business logic. Routing (ATS vs generic careers-page
// scraping) lives in lib/vacancies/londonDirectory.ts.

/** London market participant segments (Section 4 coverholders fold into mga_coverholder). */
export type LondonMarketSegment =
  | "lloyds_syndicate"
  | "company_market"
  | "mga_coverholder"
  | "broker";

/** ATS platform detected from the careers URL; careers_page = generic HTML site. */
export type LondonPlatformHint =
  | "workday"
  | "teamtailor"
  | "recruitee"
  | "workable"
  | "careers_page";

export interface LondonInsuranceEmployer {
  name: string;
  careersUrl: string;
  segment: LondonMarketSegment;
  platformHint: LondonPlatformHint;
  sectorTag: "insurance";
  notes?: string;
}

export const LONDON_INSURANCE_EMPLOYERS: LondonInsuranceEmployer[] = [
  {
    name: "Acrisure Re",
    careersUrl: "https://www.acrisure.com/careers",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "AmWins Global Risks",
    careersUrl: "https://www.amwins.com/careers",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Aon Ltd",
    careersUrl: "https://jobs.aon.com",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Ardonagh Group",
    careersUrl: "https://ardonaghspeciality.teamtailor.com",
    segment: "broker",
    platformHint: "teamtailor",
    sectorTag: "insurance",
  },
  {
    name: "BMS Group",
    careersUrl: "https://jobs.bms.com/careers",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Chesterfield Insurance Brokers Ltd",
    careersUrl: "https://www.chesterfieldinsurance.co.uk",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Citynet Insurance Brokers Ltd",
    careersUrl: "https://www.citynet.co.uk",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Decus Insurance Brokers Ltd",
    careersUrl: "https://www.decus.co.uk",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Ed Broking LLP",
    careersUrl: "https://www.edbroking.com/careers",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Elmore Insurance Brokers Ltd",
    careersUrl: "https://www.elmore.co.uk/careers",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Fenchurch Faris Ltd",
    careersUrl: "https://www.fenchurchfaris.com",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Gallagher (AJG UK)",
    careersUrl: "https://jobs.ajg.com/ajg-uk",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Gallagher Re / Gallagher Specialty",
    careersUrl: "https://jobs.ajg.com/ajg-uk",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Guy Carpenter & Co GmbH",
    careersUrl: "https://careers.marsh.com",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "H W Wood Ltd",
    careersUrl: "https://www.hwwood.co.uk",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Howden Insurance Brokers Ltd",
    careersUrl: "https://www.howdengroupholdings.com/careers-and-culture",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Howden Reinsurance Brokers Limited",
    careersUrl: "https://www.howdengroupholdings.com/careers-and-culture",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Howden Specialty Limited",
    careersUrl: "https://www.howdengroupholdings.com/careers-and-culture",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Incepta Risk Management Ltd",
    careersUrl: "https://www.inceptarisk.com",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Iris Insurance Brokers Ltd",
    careersUrl: "https://www.irisbrokers.co.uk",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "J B Boda & Co (UK) Ltd",
    careersUrl: "https://www.jbboda.net",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Kerry London Ltd",
    careersUrl: "https://www.kerrylondon.co.uk",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Lime Street Insurance Brokers Limited",
    careersUrl: "https://www.limestreet.co.uk",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Lloyd & Partners Limited",
    careersUrl: "https://www.lloydandpartners.co.uk",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Lockton Group Companies International",
    careersUrl: "https://careers.lockton.com/gb/en",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Marine Aviation & General (London) Ltd",
    careersUrl: "https://www.mag-london.co.uk",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Marsh Ltd",
    careersUrl: "https://careers.marsh.com",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "McGill and Partners",
    careersUrl: "https://mcgillpartners.com/career-opportunities/",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Miles Smith Broking Ltd",
    careersUrl: "https://www.milessmith.co.uk",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Miller Insurance Services LLP",
    careersUrl: "https://www.miller-insurance.com/careers/jobs",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "MNK International Ltd",
    careersUrl: "https://www.mnkre.com",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "New Dawn Risk Group Ltd",
    careersUrl: "https://www.newdawnrisk.com/careers",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Oneglobal Broking Services Ltd",
    careersUrl: "https://www.oneglobal-broking.com",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Paragon International Insurance Brokers",
    careersUrl: "https://www.paragonbrokers.com/careers",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "PIB Group",
    careersUrl: "https://www.pib-group.com/careers",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Price Forbes & Partners Ltd",
    careersUrl: "https://ardonaghspeciality.teamtailor.com",
    segment: "broker",
    platformHint: "teamtailor",
    sectorTag: "insurance",
  },
  {
    name: "Price Forbes Re (Ardonagh Specialty)",
    careersUrl: "https://ardonaghspeciality.teamtailor.com",
    segment: "broker",
    platformHint: "teamtailor",
    sectorTag: "insurance",
  },
  {
    name: "Safeonline LLP",
    careersUrl: "https://www.safeonline.com",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Seascope Insurance Services Ltd",
    careersUrl: "https://www.seascope.co.uk",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Shepherd Compello Ltd",
    careersUrl: "https://www.shepherdcompello.com",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Special Contingency Risks Ltd",
    careersUrl: "https://www.scr.co.uk",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Specialist Risk Group",
    careersUrl: "https://www.srg.co.uk/careers",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Tysers Insurance Brokers Limited",
    careersUrl: "https://tysers.recruitee.com",
    segment: "broker",
    platformHint: "recruitee",
    sectorTag: "insurance",
  },
  {
    name: "United Insurance Brokers Ltd",
    careersUrl: "https://www.uib.co.uk/careers",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Verlingue London Markets Limited",
    careersUrl: "https://www.verlingue.co.uk",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Whitehall Court Insurance Brokers Limited",
    careersUrl: "https://www.whitehallcourt.co.uk",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Willis Towers Watson (WTW)",
    careersUrl: "https://careers.wtwco.com",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Xact Risk Solutions Ltd",
    careersUrl: "https://www.xactrisk.com",
    segment: "broker",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Accelerant Insurance Europe Limited",
    careersUrl: "https://www.accelerant.eu/careers",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Advent Risk Management",
    careersUrl: "https://www.adventrisk.com",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "AIG UK Ltd",
    careersUrl: "https://www.aig.com/careers",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Allianz Global Corporate & Specialty SE",
    careersUrl: "https://www.allianz.com/en/careers.html",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Allied World Assurance Company (Europe) DAC",
    careersUrl: "https://www.awac.com/careers",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "AmTrust Specialty Limited",
    careersUrl: "https://careers.amtrustfinancial.com",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Casualty, Professional; Casualty, A&H; also listed as: mga_coverholder",
  },
  {
    name: "Antares Reinsurance Company Limited",
    careersUrl: "https://www.antaresuw.com",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Arch Insurance (UK) Limited",
    careersUrl: "https://www.archinsurance.com/careers",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Aspen Insurance UK Limited (AIUK)",
    careersUrl: "https://www.aspen.co/careers",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Assicurazioni Generali (UK Branch)",
    careersUrl: "https://www.generali.com/careers",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Aviva Insurance Limited",
    careersUrl: "https://careers.aviva.co.uk",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "AXA XL Insurance Company UK Limited",
    careersUrl: "https://careers.axa.com/axa-entities/axa-xl",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Axis Specialty Europe SE",
    careersUrl: "https://www.axiscapital.com/careers",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Berkshire Hathaway European Insurance DAC",
    careersUrl: "https://www.berkshirehathaway.com",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Berkshire Hathaway International Insurance Ltd",
    careersUrl: "https://www.berkshirehathaway.com",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "CFC Underwriting Limited",
    careersUrl: "https://www.cfc.com/en-us/careers/",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Cyber, Professional Lines; also listed as: mga_coverholder",
  },
  {
    name: "Chaucer Insurance Company DAC",
    careersUrl: "https://careers.chaucergroup.com",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Chubb European Group SE",
    careersUrl: "https://careers.chubb.com",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "CNA Insurance Company Limited",
    careersUrl: "https://www.cnainsurance.com",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Conduit Reinsurance Limited",
    careersUrl: "https://www.conduitre.com/careers",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Convex Insurance UK Limited",
    careersUrl: "https://convexin.pinpointhq.com/en",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Specialty, Reinsurance; also listed as: mga_coverholder",
  },
  {
    name: "Coverys Limited",
    careersUrl: "https://www.coverys.com/careers",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Endurance Worldwide Insurance Limited",
    careersUrl: "https://www.sompo-intl.com/careers",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Euler Hermes S.A. (Allianz Trade)",
    careersUrl: "https://www.allianz.com/en/careers.html",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Everest Insurance (Ireland) DAC",
    careersUrl: "https://www.everestgre.com/careers",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Gard Marine and Energy Europe AS",
    careersUrl: "https://www.gard.no/careers",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "General Reinsurance Company",
    careersUrl: "https://www.genre.com/careers",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Global Aerospace Underwriting Managers (GAUM)",
    careersUrl: "https://www.global-aero.com",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Great Lakes Insurance SE (UK Branch)",
    careersUrl: "https://www.munichre.com/en/solutions/for-industry-clients/careers.html",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Hamilton Insurance DAC",
    careersUrl: "https://www.hamiltongroup.com/careers",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Hannover Rueck SE",
    careersUrl: "https://www.hannover-re.com/careers",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "HDI Global SE – UK",
    careersUrl: "https://www.hdi.global/careers",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "HDI Global Specialty SE",
    careersUrl: "https://www.hdi.global/careers",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "HSB Engineering Insurance Limited",
    careersUrl: "https://www.munichre.com",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "International General Insurance Company (UK) Ltd",
    careersUrl: "https://www.iginsure.com/careers",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Lancashire Insurance Company (UK) Limited",
    careersUrl: "https://www.lancashiregroup.com/careers",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Liberty Mutual Insurance Europe SE",
    careersUrl: "https://jobs.libertymutualgroup.com",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Markel Insurance SE",
    careersUrl: "https://www.markel.com/about-us/careers",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Markel International Insurance Company Limited",
    careersUrl: "https://www.markel.com/about-us/careers",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Mitsui Sumitomo Insurance (Europe) Limited",
    careersUrl: "https://www.ms-ins.com",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "MS Amlin Insurance SE",
    careersUrl: "https://www.msamlin.com/careers/",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "New India Assurance Company Limited",
    careersUrl: "https://www.newindia.co.in",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "NorthStandard Limited",
    careersUrl: "https://www.northstandardclub.com/careers",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "QBE UK Limited",
    careersUrl: "https://www.qbe.com/careers",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Renaissance Re Europe AG, UK Branch",
    careersUrl: "https://www.renre.com/careers",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Royal & Sun Alliance Insurance Group Limited",
    careersUrl: "https://www.rsagroup.com/careers",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "SCOR UK Company Limited",
    careersUrl: "https://www.scor.com/en/careers",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Sirius Point International Insurance Corporation",
    careersUrl: "https://www.siriuspoint.com/careers",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Starr International (Europe) Limited",
    careersUrl: "https://www.starrcompanies.com/careers",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Swiss Re Europe S.A., UK Branch",
    careersUrl: "https://www.swissre.com/careers.html",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Swiss Re International SE",
    careersUrl: "https://www.swissre.com/careers.html",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "The Fidelis Partnership",
    careersUrl: "https://www.fidelisinsurance.com/careers",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "TransRe London Limited",
    careersUrl: "https://www.transre.com/careers",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Travelers Insurance Company",
    careersUrl: "https://www.travelers.com/careers",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "WE Bell & Clements Ltd (Munich Re Specialty)",
    careersUrl: "https://www.munichre.com",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "Zurich Insurance Company Ltd (UK)",
    careersUrl: "https://www.zurich.co.uk/careers",
    segment: "company_market",
    platformHint: "careers_page",
    sectorTag: "insurance",
  },
  {
    name: "AEGIS Managing Agency Limited",
    careersUrl: "https://www.aegislondon.co.uk",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicate 1225",
  },
  {
    name: "Allied World Managing Agency Limited",
    careersUrl: "https://www.awac.com/careers",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicate 2232",
  },
  {
    name: "Antares Managing Agency Limited",
    careersUrl: "https://www.antaresuw.com",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicate 1274",
  },
  {
    name: "Apollo Syndicate Management Limited",
    careersUrl: "https://www.apollounderwriting.com/careers",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicates 1925, 1969, 1971, 1994",
  },
  {
    name: "Arch Managing Agency Limited",
    careersUrl: "https://www.archinsurance.com/careers",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicates 1955, 2012",
  },
  {
    name: "Argenta Syndicate Management Limited",
    careersUrl: "https://www.argentagroup.com",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicates 2121, 6134",
  },
  {
    name: "Ariel Re Managing Agency Limited",
    careersUrl: "https://www.arielre.com/careers/",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicates 1910, 6117; Reinsurance; also listed as: mga_coverholder",
  },
  {
    name: "Ark Syndicate Management Limited",
    careersUrl: "https://www.arkunderwriting.com/careers",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicates 3902, 4020",
  },
  {
    name: "Ascot Underwriting Limited",
    careersUrl: "https://www.ascotgroup.com/en-gb/careers/",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicate 1414; Specialty multi-line; also listed as: mga_coverholder",
  },
  {
    name: "Aspen Managing Agency Limited",
    careersUrl: "https://www.aspen.co/careers",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicate 4711",
  },
  {
    name: "Asta Managing Agency Limited",
    careersUrl: "https://www.astacapital.co.uk",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicates 1322, 1416, 1609, 1699, 1796, 1892, 1902, 1922, 1985, 1988",
  },
  {
    name: "Atrium Underwriters Limited",
    careersUrl: "https://www.atriumuw.com/careers",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicate 609; Multi-line; also listed as: mga_coverholder",
  },
  {
    name: "AXA XL Underwriting Agencies Limited",
    careersUrl: "https://careers.axa.com/axa-entities/axa-xl",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicates 2003, 3002",
  },
  {
    name: "Axis Managing Agency Limited",
    careersUrl: "https://www.axiscapital.com/careers",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicate 1686",
  },
  {
    name: "Beazley Furlonge Limited",
    careersUrl: "https://careers.beazley.com/jobs",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicates 623, 2623, 3622, 3623, 5623, 6107",
  },
  {
    name: "Blenheim Underwriting Limited",
    careersUrl: "https://www.blenheim-uw.com",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicate 5886",
  },
  {
    name: "Brit Syndicates Limited",
    careersUrl: "https://www.britinsurance.com/careers-at-brit-insurance",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicates 1618, 2987, 2988; Specialty; also listed as: mga_coverholder",
  },
  {
    name: "Canopius Managing Agents Limited",
    careersUrl: "https://www.canopius.com/careers-with-canopius/",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicate 4444; Specialty; also listed as: mga_coverholder",
  },
  {
    name: "Chaucer Syndicates Limited",
    careersUrl: "https://careers.chaucergroup.com",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicates 1084, 1176",
  },
  {
    name: "Chubb Underwriting Agencies Limited",
    careersUrl: "https://careers.chubb.com",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicate 2488",
  },
  {
    name: "Cincinnati Global Underwriting Agency Limited",
    careersUrl: "https://www.iquw.com/careers",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicate 318",
  },
  {
    name: "Dale Managing Agency Limited",
    careersUrl: "https://www.daleunderwriting.com",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicate 1729",
  },
  {
    name: "Faraday Underwriting Limited",
    careersUrl: "https://www.faraday.com/careers",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicate 435",
  },
  {
    name: "Hamilton Managing Agency Limited",
    careersUrl: "https://www.hamiltongroup.com/careers",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicates 1947, 4000; Specialty Re; also listed as: mga_coverholder",
  },
  {
    name: "Hardy (Underwriting Agencies) / CNA Hardy",
    careersUrl: "https://careers.chaucergroup.com",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicate 382",
  },
  {
    name: "Hartford Underwriting Agency Limited",
    careersUrl: "https://www.thehartford.com/careers",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicate 1221; also listed as: company_market",
  },
  {
    name: "HCC Underwriting Agency Limited",
    careersUrl: "https://www.tokiomarinegroup.com",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicate 4141",
  },
  {
    name: "Hiscox Syndicates Limited",
    careersUrl: "https://hiscox.wd3.myworkdayjobs.com/Hiscox_External_Site",
    segment: "lloyds_syndicate",
    platformHint: "workday",
    sectorTag: "insurance",
    notes: "Lloyd's syndicates 33, 3624, 6104",
  },
  {
    name: "Inigo Managing Agent Limited",
    careersUrl: "https://inigoinsurance.com/culture-and-people/",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicate 1301",
  },
  {
    name: "IQUW Syndicate Management Limited",
    careersUrl: "https://www.iquw.com/careers",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicates 218, 1856",
  },
  {
    name: "Lancashire Syndicates Limited",
    careersUrl: "https://www.lancashiregroup.com/careers",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicates 2010, 3010; Property Re; also listed as: mga_coverholder",
  },
  {
    name: "Liberty Managing Agency Limited",
    careersUrl: "https://www.libertymutual.com/careers",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicate 4472",
  },
  {
    name: "Managing Agency Partners Limited",
    careersUrl: "https://www.mapunderwriting.co.uk",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicates 2791, 6103",
  },
  {
    name: "Markel Syndicate Management Limited",
    careersUrl: "https://www.markel.com/about-us/careers",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicate 3000",
  },
  {
    name: "MS Amlin Underwriting Limited",
    careersUrl: "https://www.msamlin.com/careers/",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicate 2001",
  },
  {
    name: "Munich Re Syndicate Limited",
    careersUrl: "https://www.munichre.com/en/solutions/for-industry-clients/careers.html",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicate 457",
  },
  {
    name: "Nephila Syndicate Management Limited",
    careersUrl: "https://www.nephila.com",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicates 2357, 2358",
  },
  {
    name: "Newline Underwriting Management Limited",
    careersUrl: "https://www.newlinegroup.com",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicate 1218; Specialty; also listed as: mga_coverholder",
  },
  {
    name: "Polo Managing Agency Limited",
    careersUrl: "https://www.poloworks.com",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicate 1996",
  },
  {
    name: "Probitas Managing Agency Limited",
    careersUrl: "https://www.probitas1492.com",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicates 1492, 2024",
  },
  {
    name: "QBE Underwriting Limited",
    careersUrl: "https://www.qbe.com/careers",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicates 386, 2999",
  },
  {
    name: "RenaissanceRe Syndicate Management Limited",
    careersUrl: "https://www.renre.com/careers",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicate 1458",
  },
  {
    name: "S A Meacock & Company Limited",
    careersUrl: "https://www.saameacock.co.uk",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicate 727",
  },
  {
    name: "SCOR Managing Agency Limited",
    careersUrl: "https://www.scor.com/en/careers",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicate 2015",
  },
  {
    name: "Sirius International Managing Agency Limited",
    careersUrl: "https://www.siriuspoint.com",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicate 1945",
  },
  {
    name: "Starr Managing Agents Limited",
    careersUrl: "https://www.starrcompanies.com/careers",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicate 1919",
  },
  {
    name: "Talbot Underwriting Limited",
    careersUrl: "https://www.talbot-uw.com",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicates 1183, 2019",
  },
  {
    name: "Tokio Marine Kiln Syndicates Limited",
    careersUrl: "https://www.tmkiln.com/careers/",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicates 510, 1880",
  },
  {
    name: "Travelers Syndicate Management Limited",
    careersUrl: "https://www.travelers.com/careers",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicate 5000",
  },
  {
    name: "W R Berkley Syndicate Management Limited",
    careersUrl: "https://www.berkley.com/careers",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicate 1967",
  },
  {
    name: "Westfield Specialty Managing Agency Ltd",
    careersUrl: "https://www.westfieldspecialty.com",
    segment: "lloyds_syndicate",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Lloyd's syndicate 1200",
  },
  {
    name: "Azura Global Risks",
    careersUrl: "https://www.azuraglobalrisks.com",
    segment: "mga_coverholder",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Multi-line",
  },
  {
    name: "Beazley (Delegated)",
    careersUrl: "https://careers.beazley.com/jobs",
    segment: "mga_coverholder",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Specialty; Specialty multi-line",
  },
  {
    name: "Brady Underwriting",
    careersUrl: "https://www.bradyunderwriting.ie",
    segment: "mga_coverholder",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Casualty, A&H, Property",
  },
  {
    name: "Carisma Group",
    careersUrl: "https://www.carismagroup.ie",
    segment: "mga_coverholder",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Fleet, niche",
  },
  {
    name: "Casper Specialty UK",
    careersUrl: "https://www.casper-specialty.com",
    segment: "mga_coverholder",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Casualty, FI, Cyber; FI, Professional Lines, Cyber",
  },
  {
    name: "Cincinnati Global Underwriting",
    careersUrl: "https://www.cinfin.com/careers",
    segment: "mga_coverholder",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Property, Specialty",
  },
  {
    name: "Clearwater UW Ltd",
    careersUrl: "https://www.clearwateruw.com",
    segment: "mga_coverholder",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Specialty",
  },
  {
    name: "Cooper Gay (Ardonagh Specialty)",
    careersUrl: "https://ardonaghspeciality.teamtailor.com",
    segment: "mga_coverholder",
    platformHint: "teamtailor",
    sectorTag: "insurance",
    notes: "Multi-line",
  },
  {
    name: "DUAL Group",
    careersUrl: "https://www.dualgroup.com/careers",
    segment: "mga_coverholder",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Multi-line specialty",
  },
  {
    name: "Focus Underwriting",
    careersUrl: "https://www.focus-underwriting.co.uk",
    segment: "mga_coverholder",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Construction",
  },
  {
    name: "Global Aerospace Underwriting (GAUM)",
    careersUrl: "https://www.global-aero.com",
    segment: "mga_coverholder",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Aviation",
  },
  {
    name: "Globe Underwriting (Ardonagh Specialty)",
    careersUrl: "https://ardonaghspeciality.teamtailor.com",
    segment: "mga_coverholder",
    platformHint: "teamtailor",
    sectorTag: "insurance",
    notes: "Cyber, Marine, PV",
  },
  {
    name: "Greenlight Re Innovations",
    careersUrl: "https://www.greenlightre.ky",
    segment: "mga_coverholder",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Parametric, tech-driven",
  },
  {
    name: "Hathaway and Cope",
    careersUrl: "https://www.hathawayandcope.co.uk",
    segment: "mga_coverholder",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Liability schemes",
  },
  {
    name: "Hiscox (Coverholder platforms)",
    careersUrl: "https://hiscox.wd3.myworkdayjobs.com/Hiscox_External_Site",
    segment: "mga_coverholder",
    platformHint: "workday",
    sectorTag: "insurance",
    notes: "Specialty, professional",
  },
  {
    name: "Ignite Specialty Risk",
    careersUrl: "https://www.ignitespecialtyrisk.com",
    segment: "mga_coverholder",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Litigation risk",
  },
  {
    name: "Inigo Insurance",
    careersUrl: "https://inigoinsurance.com/culture-and-people/",
    segment: "mga_coverholder",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Data-driven specialty",
  },
  {
    name: "IQUW",
    careersUrl: "https://www.iquw.com/careers",
    segment: "mga_coverholder",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Specialty",
  },
  {
    name: "KGM (DUAL UK)",
    careersUrl: "https://www.dualgroup.com/careers",
    segment: "mga_coverholder",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Specialist motor",
  },
  {
    name: "M & M Underwriting Limited",
    careersUrl: "https://www.mmunderwriting.co.uk",
    segment: "mga_coverholder",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Product liability",
  },
  {
    name: "Markel International",
    careersUrl: "https://www.markel.com/about-us/careers",
    segment: "mga_coverholder",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Specialty multi-line; Specialty",
  },
  {
    name: "Mosaic Insurance (via Asta)",
    careersUrl: "https://www.mosaicinsurance.com/careers",
    segment: "mga_coverholder",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Specialty",
  },
  {
    name: "Optimum Speciality Risks (OSR)",
    careersUrl: "https://www.optimumspecialtyrisks.com",
    segment: "mga_coverholder",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Cyber",
  },
  {
    name: "Pen Underwriting",
    careersUrl: "https://www.penunderwriting.com/careers",
    segment: "mga_coverholder",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Multi-line",
  },
  {
    name: "Plum Underwriting",
    careersUrl: "https://www.plumunderwriting.co.uk",
    segment: "mga_coverholder",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Specialist home",
  },
  {
    name: "Portsoken Limited",
    careersUrl: "https://www.portsoken.com",
    segment: "mga_coverholder",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Recruitment & employment agency sector; Recruitment sector PI/PL",
  },
  {
    name: "Rising Edge Ltd",
    careersUrl: "https://www.risingedge.com",
    segment: "mga_coverholder",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "W&I, Transactional",
  },
  {
    name: "Rokstone (Aventum Group)",
    careersUrl: "https://www.aventumgroup.com",
    segment: "mga_coverholder",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Specialty",
  },
  {
    name: "TAP Underwriting",
    careersUrl: "https://www.tapunderwriting.com",
    segment: "mga_coverholder",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Commercial auto (N. America)",
  },
  {
    name: "Tokio Marine Kiln (MGA Platform)",
    careersUrl: "https://www.tmkiln.com/careers/",
    segment: "mga_coverholder",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Multi-line",
  },
  {
    name: "Vault MGA Limited",
    careersUrl: "https://www.vaultmga.com",
    segment: "mga_coverholder",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Surety, structured credit",
  },
  {
    name: "Virtu Underwriting",
    careersUrl: "https://www.virtuunderwriting.co.uk",
    segment: "mga_coverholder",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Fine Art, Private Client",
  },
  {
    name: "Wrisk Transfer Ltd",
    careersUrl: "https://www.wrisk.co/careers",
    segment: "mga_coverholder",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Subscription motor",
  },
  {
    name: "Yutree Underwriting",
    careersUrl: "https://www.yutree.co.uk",
    segment: "mga_coverholder",
    platformHint: "careers_page",
    sectorTag: "insurance",
    notes: "Liability schemes; Liability, Property",
  },
];

/** Directory rows that could not be included (e.g. no careers URL published). */
export const LONDON_DIRECTORY_UNRESOLVED: Array<{
  name: string;
  segment: LondonMarketSegment;
  reason: string;
}> = [
  { name: "Bernard Maitland Ltd", segment: "mga_coverholder", reason: "no careers URL in directory" },
];
