import type { CuratedTitleEntry } from "./types";

/**
 * Curated accountancy-practice and in-house finance job titles.
 *
 * This is a CROSS-INDUSTRY sector ("accountancy_finance"): finance roles
 * exist inside insurers, banks, asset managers and everywhere else. Bare
 * finance titles (CFO, Financial Controller, Management Accountant,
 * Treasury Analyst, Internal Auditor, FP&A Analyst…) resolve here; the
 * sector-specific files claim them only with an industry qualifier
 * (e.g. "Chief Financial Officer (Banking)", "Management Accountant
 * (Asset Management)") — exact matches always beat contained matches,
 * so the qualified forms win for those vacancies.
 *
 * The spec's finer families (executive_leadership, practice, audit_assurance,
 * tax, accounts_bookkeeping_payroll, financial_reporting, fpa_commercial,
 * treasury_corporate_finance, credit_billing_ar_ap, finance_systems_change)
 * live in `tags`; `family` is a FinFunction as in the other files.
 *
 * FALSE-POSITIVE NOTE: the supplied bare "Business Partner" is deliberately
 * NOT ingested (it would swallow HR/IT Business Partner roles); it is
 * represented by the "Finance Business Partner" canonical group instead.
 *
 * PASTE ADDITIONAL TITLES HERE following the same shape.
 */
export const ACCOUNTANCY_FINANCE_TITLES: CuratedTitleEntry[] = [
  // ── Executive leadership ─────────────────────────────────────────────────
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Chief Financial Officer",
    variants: ["group chief financial officer", "interim chief financial officer"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Finance Director",
    variants: ["group finance director", "director of finance"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Group Financial Controller",
    variants: ["group controller"],
    seniority: "senior",
    tags: ["executive_leadership", "financial_reporting"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Financial Controller",
    variants: ["finance controller"],
    seniority: "senior",
    tags: ["executive_leadership", "financial_reporting"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Head of Finance",
    variants: ["finance lead"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Head of Management Reporting",
    variants: ["management reporting manager"],
    seniority: "executive",
    tags: ["executive_leadership", "financial_reporting"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Head of Financial Reporting",
    variants: ["financial reporting director"],
    seniority: "executive",
    tags: ["executive_leadership", "financial_reporting"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Head of Tax",
    variants: ["group head of tax", "tax lead"],
    seniority: "executive",
    tags: ["executive_leadership", "tax"],
  },
  {
    industry: "accountancy_finance",
    family: "compliance",
    canonicalTitle: "Head of Internal Audit",
    variants: ["internal audit director", "group head of internal audit"],
    seniority: "executive",
    tags: ["executive_leadership", "audit_assurance"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Head of Treasury",
    variants: ["group treasurer", "treasury director"],
    seniority: "executive",
    tags: ["executive_leadership", "treasury_corporate_finance"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Head of FP&A",
    variants: ["head of financial planning and analysis", "fp&a director"],
    seniority: "executive",
    tags: ["executive_leadership", "fpa_commercial"],
  },

  // ── Accountancy practice ─────────────────────────────────────────────────
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Partner (Accountancy Practice)",
    variants: ["accountancy practice partner", "accountancy partner", "equity partner accountancy", "salaried partner accountancy"],
    seniority: "executive",
    tags: ["practice"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Director (Accountancy Practice)",
    variants: ["accountancy practice director", "accountancy director"],
    seniority: "senior",
    tags: ["practice"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Senior Manager (Accountancy Practice)",
    variants: ["accountancy practice senior manager", "accountancy senior manager"],
    seniority: "senior",
    tags: ["practice"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Manager (Accountancy Practice)",
    variants: ["accountancy practice manager", "accountancy manager"],
    tags: ["practice"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Assistant Manager (Accountancy Practice)",
    variants: ["accountancy practice assistant manager", "accountancy assistant manager"],
    tags: ["practice"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Client Manager (Accountancy Practice)",
    variants: ["client manager accountancy", "accountancy client manager", "portfolio manager accountancy practice"],
    tags: ["practice"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Outsourcing Manager (Accountancy)",
    variants: ["outsourcing manager accountancy", "accounting outsourcing manager"],
    tags: ["practice"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Practice Accountant",
    variants: ["accountancy practice accountant"],
    tags: ["practice"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Accounts Senior",
    variants: ["senior accounts technician"],
    tags: ["practice"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Semi-Senior Accountant",
    variants: ["semi senior accountant", "accounts semi senior"],
    tags: ["practice"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Accounts Assistant",
    variants: ["assistant accountant", "accounts junior"],
    seniority: "junior",
    tags: ["accounts_bookkeeping_payroll"],
  },

  // ── Audit & assurance ────────────────────────────────────────────────────
  {
    industry: "accountancy_finance",
    family: "compliance",
    canonicalTitle: "Audit Partner",
    variants: ["assurance partner"],
    seniority: "executive",
    tags: ["audit_assurance"],
  },
  {
    industry: "accountancy_finance",
    family: "compliance",
    canonicalTitle: "Audit Director",
    variants: ["assurance director"],
    seniority: "senior",
    tags: ["audit_assurance"],
  },
  {
    industry: "accountancy_finance",
    family: "compliance",
    canonicalTitle: "Audit Senior Manager",
    variants: ["senior audit manager", "assurance senior manager"],
    seniority: "senior",
    tags: ["audit_assurance"],
  },
  {
    industry: "accountancy_finance",
    family: "compliance",
    canonicalTitle: "Audit Manager",
    variants: ["external audit manager", "assurance manager"],
    tags: ["audit_assurance"],
  },
  {
    industry: "accountancy_finance",
    family: "compliance",
    canonicalTitle: "Assistant Audit Manager",
    variants: ["audit assistant manager"],
    tags: ["audit_assurance"],
  },
  {
    industry: "accountancy_finance",
    family: "compliance",
    canonicalTitle: "Audit Senior",
    variants: ["senior auditor", "external audit senior"],
    seniority: "senior",
    tags: ["audit_assurance"],
  },
  {
    industry: "accountancy_finance",
    family: "compliance",
    canonicalTitle: "Auditor",
    variants: ["external auditor"],
    tags: ["audit_assurance"],
  },
  {
    industry: "accountancy_finance",
    family: "compliance",
    canonicalTitle: "Junior Auditor",
    variants: ["audit junior", "trainee auditor", "audit trainee"],
    seniority: "junior",
    tags: ["audit_assurance"],
  },
  {
    industry: "accountancy_finance",
    family: "compliance",
    canonicalTitle: "Internal Auditor",
    variants: ["internal audit analyst"],
    tags: ["audit_assurance"],
  },
  {
    industry: "accountancy_finance",
    family: "compliance",
    canonicalTitle: "Senior Internal Auditor",
    variants: ["internal audit senior"],
    seniority: "senior",
    tags: ["audit_assurance"],
  },
  {
    industry: "accountancy_finance",
    family: "compliance",
    canonicalTitle: "Internal Audit Manager",
    variants: ["internal audit senior manager"],
    tags: ["audit_assurance"],
  },

  // ── Tax ──────────────────────────────────────────────────────────────────
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Tax Partner",
    variants: [],
    seniority: "executive",
    tags: ["tax"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Tax Director",
    variants: ["group tax director"],
    seniority: "senior",
    tags: ["tax"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Senior Tax Manager",
    variants: ["tax senior manager"],
    seniority: "senior",
    tags: ["tax"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Tax Manager",
    variants: ["group tax manager"],
    tags: ["tax"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Assistant Tax Manager",
    variants: ["tax assistant manager"],
    tags: ["tax"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Tax Senior",
    variants: ["senior tax associate", "tax senior associate"],
    seniority: "senior",
    tags: ["tax"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Tax Consultant",
    variants: ["tax adviser", "tax advisor", "tax associate"],
    tags: ["tax"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Corporate Tax Manager",
    variants: ["corporation tax manager"],
    tags: ["tax"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Personal Tax Manager",
    variants: ["private client tax manager"],
    tags: ["tax"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "VAT Manager",
    variants: ["vat senior manager"],
    tags: ["tax"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "VAT Consultant",
    variants: ["vat adviser", "vat advisor", "vat specialist"],
    tags: ["tax"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Indirect Tax Specialist",
    variants: ["indirect tax manager", "indirect tax consultant"],
    tags: ["tax"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Transfer Pricing Specialist",
    variants: ["transfer pricing manager", "transfer pricing analyst"],
    tags: ["tax"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Tax Compliance Manager",
    variants: ["tax compliance specialist"],
    tags: ["tax"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Tax Reporting Manager",
    variants: ["tax reporting specialist"],
    tags: ["tax"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "M&A Tax Manager",
    variants: ["m&a tax specialist", "transaction tax manager"],
    tags: ["tax", "treasury_corporate_finance"],
  },

  // ── Accounts, bookkeeping & payroll ──────────────────────────────────────
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Bookkeeper",
    variants: [],
    tags: ["accounts_bookkeeping_payroll"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Senior Bookkeeper",
    variants: [],
    seniority: "senior",
    tags: ["accounts_bookkeeping_payroll"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Payroll Administrator",
    variants: ["payroll assistant", "payroll clerk"],
    tags: ["accounts_bookkeeping_payroll"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Payroll Officer",
    variants: ["payroll specialist"],
    tags: ["accounts_bookkeeping_payroll"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Payroll Manager",
    variants: ["payroll supervisor", "payroll team leader"],
    tags: ["accounts_bookkeeping_payroll"],
  },

  // ── Financial reporting ──────────────────────────────────────────────────
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Financial Accountant",
    variants: ["qualified financial accountant"],
    tags: ["financial_reporting"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Senior Financial Accountant",
    variants: [],
    seniority: "senior",
    tags: ["financial_reporting"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Management Accountant",
    variants: ["assistant management accountant"],
    tags: ["financial_reporting"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Senior Management Accountant",
    variants: [],
    seniority: "senior",
    tags: ["financial_reporting"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Group Accountant",
    variants: ["group reporting accountant"],
    tags: ["financial_reporting"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Reporting Accountant",
    variants: ["financial reporting accountant"],
    tags: ["financial_reporting"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Statutory Reporting Accountant",
    variants: ["statutory accountant", "statutory accounts accountant"],
    tags: ["financial_reporting"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Consolidations Accountant",
    variants: ["consolidation accountant", "group consolidations accountant"],
    tags: ["financial_reporting"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Technical Accountant",
    variants: ["technical accounting manager", "accounting policy specialist"],
    tags: ["financial_reporting"],
  },

  // ── FP&A & commercial finance ────────────────────────────────────────────
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "FP&A Analyst",
    variants: ["fp&a analyst", "financial planning and analysis analyst", "fpa analyst", "financial planning analyst"],
    tags: ["fpa_commercial"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Senior FP&A Analyst",
    variants: ["senior financial planning and analysis analyst"],
    seniority: "senior",
    tags: ["fpa_commercial"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "FP&A Manager",
    variants: ["financial planning and analysis manager"],
    tags: ["fpa_commercial"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Commercial Finance Analyst",
    variants: ["commercial analyst finance"],
    tags: ["fpa_commercial"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Commercial Finance Manager",
    variants: ["commercial finance lead"],
    tags: ["fpa_commercial"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Finance Business Partner",
    variants: ["commercial finance business partner", "fp&a business partner"],
    tags: ["fpa_commercial"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Senior Finance Business Partner",
    variants: ["lead finance business partner"],
    seniority: "senior",
    tags: ["fpa_commercial"],
  },

  // ── Treasury & corporate finance ─────────────────────────────────────────
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Treasury Analyst",
    variants: ["group treasury analyst", "corporate treasury analyst"],
    tags: ["treasury_corporate_finance"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Treasury Manager",
    variants: ["group treasury manager", "corporate treasury manager"],
    tags: ["treasury_corporate_finance"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Cash Management Analyst",
    variants: ["cash flow analyst", "cash analyst"],
    tags: ["treasury_corporate_finance"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Corporate Finance Analyst",
    variants: ["corporate finance executive"],
    tags: ["treasury_corporate_finance"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Corporate Finance Manager",
    variants: ["corporate finance associate director"],
    tags: ["treasury_corporate_finance"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Transaction Services Manager",
    variants: ["transaction services senior manager", "transaction advisory manager", "due diligence manager"],
    tags: ["treasury_corporate_finance"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Forensic Accountant",
    variants: ["forensic accounting manager"],
    tags: ["treasury_corporate_finance", "forensic"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Forensic Services Manager",
    variants: ["forensic services senior manager", "forensic investigations manager"],
    tags: ["treasury_corporate_finance", "forensic"],
  },

  // ── Credit, billing, AR & AP ─────────────────────────────────────────────
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Credit Controller",
    variants: ["credit control clerk", "credit control administrator"],
    tags: ["credit_billing_ar_ap"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Senior Credit Controller",
    variants: ["credit control supervisor"],
    seniority: "senior",
    tags: ["credit_billing_ar_ap"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Credit Manager",
    variants: ["credit control manager"],
    tags: ["credit_billing_ar_ap"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Billing Specialist",
    variants: ["billing analyst", "billing coordinator", "billing clerk"],
    tags: ["credit_billing_ar_ap"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Accounts Payable Clerk",
    variants: ["accounts payable assistant", "purchase ledger clerk", "purchase ledger assistant"],
    tags: ["credit_billing_ar_ap"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Accounts Receivable Clerk",
    variants: ["accounts receivable assistant", "sales ledger clerk", "sales ledger assistant"],
    tags: ["credit_billing_ar_ap"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Accounts Payable Manager",
    variants: ["ap manager", "purchase ledger manager"],
    tags: ["credit_billing_ar_ap"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Accounts Receivable Manager",
    variants: ["ar manager", "sales ledger manager"],
    tags: ["credit_billing_ar_ap"],
  },

  // ── Finance systems & change ─────────────────────────────────────────────
  {
    industry: "accountancy_finance",
    family: "operations",
    canonicalTitle: "Finance Systems Analyst",
    variants: ["finance systems administrator"],
    tags: ["finance_systems_change"],
  },
  {
    industry: "accountancy_finance",
    family: "operations",
    canonicalTitle: "Finance Systems Manager",
    variants: ["finance systems lead"],
    tags: ["finance_systems_change"],
  },
  {
    industry: "accountancy_finance",
    family: "operations",
    canonicalTitle: "Business Analyst (Finance)",
    variants: ["business analyst finance", "finance business analyst"],
    tags: ["finance_systems_change"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Project Accountant",
    variants: ["projects accountant"],
    tags: ["finance_systems_change"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Cost Accountant",
    variants: ["costing accountant", "cost analyst finance"],
    tags: ["finance_systems_change"],
  },
  {
    industry: "accountancy_finance",
    family: "finance",
    canonicalTitle: "Financial Modeller",
    variants: ["financial modeler", "financial modelling analyst", "financial modeling analyst"],
    tags: ["finance_systems_change"],
  },
];
