import type { CuratedTitleEntry } from "./types";

/**
 * Curated banking job titles (full supplied list, structured).
 *
 * Same rules as insurance.ts: `industry` is a FinSector, `family` a
 * FinFunction; the spec's finer families (relationship_management,
 * branch_network, credit_lending, investment_banking, treasury_balance_sheet,
 * compliance_financial_crime, operations_middle_back_office,
 * payments_transaction_banking, digital_product_change,
 * contact_centre_collections, executive_leadership) live in `tags`.
 *
 * FALSE-POSITIVE RULE: titles that also exist outside banking (e.g.
 * "Branch Manager", "Treasury Analyst", "Business Analyst", "Internal
 * Auditor", "Collections Manager") are only included with a banking
 * qualifier so retail, corporate-finance, or utilities vacancies are never
 * force-tagged banking. Single-word variants only ever match exactly.
 *
 * PASTE ADDITIONAL TITLES HERE following the same shape.
 */
export const BANKING_TITLES: CuratedTitleEntry[] = [
  // ── Executive leadership ─────────────────────────────────────────────────
  {
    industry: "banking",
    family: "operations",
    canonicalTitle: "Chief Executive Officer (Banking)",
    variants: ["bank chief executive officer", "banking ceo", "bank ceo"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "banking",
    family: "operations",
    canonicalTitle: "Chief Operating Officer (Banking)",
    variants: ["bank chief operating officer", "banking coo", "bank coo"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "banking",
    family: "finance",
    canonicalTitle: "Chief Financial Officer (Banking)",
    variants: ["bank chief financial officer", "banking cfo", "bank cfo"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "banking",
    family: "risk",
    canonicalTitle: "Chief Risk Officer (Banking)",
    variants: ["bank chief risk officer", "banking cro", "chief risk officer banking"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "banking",
    family: "compliance",
    canonicalTitle: "Chief Compliance Officer (Banking)",
    variants: ["bank chief compliance officer", "chief compliance officer banking"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "banking",
    family: "risk",
    canonicalTitle: "Chief Credit Officer",
    variants: ["head of credit"],
    seniority: "executive",
    tags: ["executive_leadership", "credit_lending"],
  },
  {
    industry: "banking",
    family: "investments",
    canonicalTitle: "Chief Investment Officer (Bank)",
    variants: ["bank chief investment officer", "chief investment officer banking"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "banking",
    family: "client_service",
    canonicalTitle: "Head of Retail Banking",
    variants: ["retail banking director"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "banking",
    family: "client_service",
    canonicalTitle: "Head of Corporate Banking",
    variants: ["corporate banking director"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "banking",
    family: "client_service",
    canonicalTitle: "Head of Commercial Banking",
    variants: ["commercial banking director"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "banking",
    family: "investments",
    canonicalTitle: "Head of Investment Banking",
    variants: ["investment banking director"],
    seniority: "executive",
    tags: ["executive_leadership", "investment_banking"],
  },
  {
    industry: "banking",
    family: "operations",
    canonicalTitle: "Head of Transaction Banking",
    variants: [],
    seniority: "executive",
    tags: ["executive_leadership", "payments_transaction_banking"],
  },
  {
    industry: "banking",
    family: "client_service",
    canonicalTitle: "Head of Private Banking",
    variants: ["private banking director"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "banking",
    family: "client_service",
    canonicalTitle: "Head of Wealth Management",
    variants: ["wealth management director"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "banking",
    family: "risk",
    canonicalTitle: "Head of Credit Risk",
    variants: ["credit risk director"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "banking",
    family: "risk",
    canonicalTitle: "Head of Market Risk",
    variants: ["market risk director"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "banking",
    family: "risk",
    canonicalTitle: "Head of Operational Risk (Banking)",
    variants: ["head of operational risk banking", "bank head of operational risk"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "banking",
    family: "compliance",
    canonicalTitle: "Head of Financial Crime",
    variants: ["financial crime director", "head of financial crime prevention"],
    seniority: "executive",
    tags: ["executive_leadership", "compliance_financial_crime"],
  },
  {
    industry: "banking",
    family: "compliance",
    canonicalTitle: "Head of Compliance (Banking)",
    variants: ["head of compliance banking", "bank head of compliance"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "banking",
    family: "compliance",
    canonicalTitle: "Head of Internal Audit (Banking)",
    variants: ["head of internal audit banking", "bank head of internal audit"],
    seniority: "executive",
    tags: ["executive_leadership", "internal_audit"],
  },
  {
    industry: "banking",
    family: "finance",
    canonicalTitle: "Head of Treasury (Banking)",
    variants: ["head of treasury banking", "bank head of treasury", "head of bank treasury"],
    seniority: "executive",
    tags: ["executive_leadership", "treasury_balance_sheet"],
  },
  {
    industry: "banking",
    family: "operations",
    canonicalTitle: "Head of Payments",
    variants: ["payments director"],
    seniority: "executive",
    tags: ["executive_leadership", "payments_transaction_banking"],
  },
  {
    industry: "banking",
    family: "operations",
    canonicalTitle: "Head of Digital Banking",
    variants: ["digital banking director"],
    seniority: "executive",
    tags: ["executive_leadership", "digital_product_change"],
  },

  // ── Relationship management ──────────────────────────────────────────────
  {
    industry: "banking",
    family: "client_service",
    canonicalTitle: "Relationship Manager (Banking)",
    variants: ["banking relationship manager", "relationship manager banking", "bank relationship manager"],
    tags: ["relationship_management"],
  },
  {
    industry: "banking",
    family: "client_service",
    canonicalTitle: "Corporate Relationship Manager",
    variants: ["corporate banking relationship manager"],
    tags: ["relationship_management"],
  },
  {
    industry: "banking",
    family: "client_service",
    canonicalTitle: "Commercial Relationship Manager",
    variants: ["commercial banking relationship manager"],
    tags: ["relationship_management"],
  },
  {
    industry: "banking",
    family: "client_service",
    canonicalTitle: "SME Relationship Manager",
    variants: ["sme banking manager", "business banking relationship manager"],
    tags: ["relationship_management"],
  },
  {
    industry: "banking",
    family: "client_service",
    canonicalTitle: "Retail Relationship Manager",
    variants: ["retail banking relationship manager"],
    tags: ["relationship_management"],
  },
  {
    industry: "banking",
    family: "client_service",
    canonicalTitle: "Private Banker",
    variants: ["private banking manager", "private client banker"],
    tags: ["relationship_management"],
  },
  {
    industry: "banking",
    family: "client_service",
    canonicalTitle: "Wealth Manager",
    variants: ["wealth management adviser"],
    tags: ["relationship_management"],
  },
  {
    industry: "banking",
    family: "client_service",
    canonicalTitle: "Wealth Advisor (Banking)",
    variants: ["wealth adviser banking", "wealth advisor banking", "banking wealth adviser"],
    tags: ["relationship_management"],
  },
  {
    industry: "banking",
    family: "client_service",
    canonicalTitle: "Premier Relationship Manager",
    variants: ["premier banking manager"],
    tags: ["relationship_management"],
  },
  {
    industry: "banking",
    family: "client_service",
    canonicalTitle: "Key Account Manager (Banking)",
    variants: ["key account manager banking"],
    tags: ["relationship_management"],
  },
  {
    industry: "banking",
    family: "client_service",
    canonicalTitle: "Client Relationship Manager (Banking)",
    variants: ["client relationship manager banking"],
    tags: ["relationship_management"],
  },

  // ── Branch network ───────────────────────────────────────────────────────
  {
    industry: "banking",
    family: "client_service",
    canonicalTitle: "Branch Manager (Banking)",
    variants: ["bank branch manager", "banking branch manager", "branch manager banking"],
    tags: ["branch_network"],
  },
  {
    industry: "banking",
    family: "client_service",
    canonicalTitle: "Deputy Branch Manager (Banking)",
    variants: ["deputy bank branch manager", "bank deputy branch manager"],
    tags: ["branch_network"],
  },
  {
    industry: "banking",
    family: "client_service",
    canonicalTitle: "Assistant Branch Manager (Banking)",
    variants: ["assistant bank branch manager", "bank assistant branch manager"],
    tags: ["branch_network"],
  },
  {
    industry: "banking",
    family: "client_service",
    canonicalTitle: "Customer Service Manager (Branch Banking)",
    variants: ["branch customer service manager", "bank customer service manager"],
    tags: ["branch_network"],
  },
  {
    industry: "banking",
    family: "client_service",
    canonicalTitle: "Personal Banker",
    variants: ["personal banking adviser", "personal banking advisor"],
    tags: ["branch_network"],
  },
  {
    industry: "banking",
    family: "client_service",
    canonicalTitle: "Customer Service Representative (Banking)",
    variants: ["banking customer service representative", "customer service representative banking", "bank customer service advisor"],
    tags: ["branch_network"],
  },
  {
    industry: "banking",
    family: "client_service",
    canonicalTitle: "Banking Associate",
    variants: ["retail banking associate"],
    tags: ["branch_network"],
  },
  {
    industry: "banking",
    family: "client_service",
    canonicalTitle: "Bank Teller",
    variants: ["bank cashier"],
    tags: ["branch_network"],
  },
  {
    industry: "banking",
    family: "client_service",
    canonicalTitle: "Universal Banker",
    variants: [],
    tags: ["branch_network"],
  },

  // ── Credit & lending ─────────────────────────────────────────────────────
  {
    industry: "banking",
    family: "risk",
    canonicalTitle: "Credit Analyst (Banking)",
    variants: ["banking credit analyst", "credit analyst banking", "bank credit analyst"],
    tags: ["credit_lending"],
  },
  {
    industry: "banking",
    family: "risk",
    canonicalTitle: "Corporate Credit Analyst",
    variants: [],
    tags: ["credit_lending"],
  },
  {
    industry: "banking",
    family: "risk",
    canonicalTitle: "Retail Credit Analyst",
    variants: ["consumer credit analyst"],
    tags: ["credit_lending"],
  },
  {
    industry: "banking",
    family: "risk",
    canonicalTitle: "Structured Credit Analyst",
    variants: [],
    tags: ["credit_lending"],
  },
  {
    industry: "banking",
    family: "risk",
    canonicalTitle: "Credit Risk Analyst (Banking)",
    variants: ["credit risk analyst banking", "banking credit risk analyst"],
    tags: ["credit_lending"],
  },
  {
    industry: "banking",
    family: "risk",
    canonicalTitle: "Credit Risk Manager (Banking)",
    variants: ["credit risk manager banking", "banking credit risk manager"],
    tags: ["credit_lending"],
  },
  {
    industry: "banking",
    family: "risk",
    canonicalTitle: "Senior Credit Officer",
    variants: ["credit officer banking"],
    seniority: "senior",
    tags: ["credit_lending"],
  },
  {
    industry: "banking",
    family: "client_service",
    canonicalTitle: "Loan Officer",
    variants: ["lending officer"],
    tags: ["credit_lending"],
  },
  {
    industry: "banking",
    family: "client_service",
    canonicalTitle: "Lending Manager",
    variants: ["loans manager banking"],
    tags: ["credit_lending"],
  },
  {
    industry: "banking",
    family: "client_service",
    canonicalTitle: "Mortgage Adviser",
    variants: ["mortgage advisor", "mortgage consultant"],
    tags: ["credit_lending"],
  },
  {
    industry: "banking",
    family: "underwriting",
    canonicalTitle: "Mortgage Underwriter",
    variants: ["mortgage underwriter banking", "residential mortgage underwriter"],
    tags: ["credit_lending"],
  },
  {
    industry: "banking",
    family: "client_service",
    canonicalTitle: "Secured Lending Specialist",
    variants: ["secured loans specialist"],
    tags: ["credit_lending"],
  },
  {
    industry: "banking",
    family: "client_service",
    canonicalTitle: "Unsecured Lending Specialist",
    variants: ["unsecured loans specialist"],
    tags: ["credit_lending"],
  },

  // ── Investment banking ───────────────────────────────────────────────────
  {
    industry: "banking",
    family: "investments",
    canonicalTitle: "Investment Banker",
    variants: [],
    tags: ["investment_banking"],
  },
  {
    industry: "banking",
    family: "investments",
    canonicalTitle: "Investment Banking Analyst",
    variants: ["analyst investment banking", "ib analyst"],
    seniority: "junior",
    tags: ["investment_banking"],
  },
  {
    industry: "banking",
    family: "investments",
    canonicalTitle: "Investment Banking Associate",
    variants: ["associate investment banking"],
    tags: ["investment_banking"],
  },
  {
    industry: "banking",
    family: "investments",
    canonicalTitle: "Vice President (Investment Banking)",
    variants: ["investment banking vice president", "vp investment banking", "investment banking vp"],
    seniority: "senior",
    tags: ["investment_banking"],
  },
  {
    industry: "banking",
    family: "investments",
    canonicalTitle: "Director (Investment Banking)",
    variants: [],
    seniority: "senior",
    tags: ["investment_banking"],
  },
  {
    industry: "banking",
    family: "investments",
    canonicalTitle: "Managing Director (Investment Banking)",
    variants: ["investment banking managing director", "managing director investment banking"],
    seniority: "executive",
    tags: ["investment_banking"],
  },
  {
    industry: "banking",
    family: "investments",
    canonicalTitle: "M&A Analyst",
    variants: ["mergers and acquisitions analyst", "m&a associate", "mergers and acquisitions associate"],
    tags: ["investment_banking"],
  },
  {
    industry: "banking",
    family: "investments",
    canonicalTitle: "Equity Capital Markets Analyst",
    variants: ["ecm analyst"],
    tags: ["investment_banking"],
  },
  {
    industry: "banking",
    family: "investments",
    canonicalTitle: "Debt Capital Markets Analyst",
    variants: ["dcm analyst"],
    tags: ["investment_banking"],
  },
  {
    industry: "banking",
    family: "investments",
    canonicalTitle: "Leveraged Finance Analyst",
    variants: ["levfin analyst"],
    tags: ["investment_banking"],
  },
  {
    industry: "banking",
    family: "investments",
    canonicalTitle: "Project Finance Analyst",
    variants: [],
    tags: ["investment_banking"],
  },
  {
    industry: "banking",
    family: "investments",
    canonicalTitle: "Structured Finance Analyst",
    variants: [],
    tags: ["investment_banking"],
  },
  {
    industry: "banking",
    family: "investments",
    canonicalTitle: "Syndicated Loans Analyst",
    variants: ["loan syndication analyst"],
    tags: ["investment_banking"],
  },

  // ── Treasury & balance sheet ─────────────────────────────────────────────
  {
    industry: "banking",
    family: "finance",
    canonicalTitle: "Treasury Analyst (Banking)",
    variants: ["treasury analyst banking", "bank treasury analyst"],
    tags: ["treasury_balance_sheet"],
  },
  {
    industry: "banking",
    family: "finance",
    canonicalTitle: "Treasury Manager (Banking)",
    variants: ["treasury manager banking", "bank treasury manager"],
    tags: ["treasury_balance_sheet"],
  },
  {
    industry: "banking",
    family: "finance",
    canonicalTitle: "ALM Analyst (Banking)",
    variants: ["alm analyst banking", "asset liability management analyst banking", "bank alm analyst"],
    tags: ["treasury_balance_sheet"],
  },
  {
    industry: "banking",
    family: "risk",
    canonicalTitle: "Liquidity Risk Analyst",
    variants: ["liquidity risk manager banking"],
    tags: ["treasury_balance_sheet"],
  },
  {
    industry: "banking",
    family: "finance",
    canonicalTitle: "Liquidity Manager (Banking)",
    variants: ["liquidity manager banking", "bank liquidity manager"],
    tags: ["treasury_balance_sheet"],
  },
  {
    industry: "banking",
    family: "finance",
    canonicalTitle: "Balance Sheet Manager",
    variants: ["balance sheet management analyst"],
    tags: ["treasury_balance_sheet"],
  },
  {
    industry: "banking",
    family: "finance",
    canonicalTitle: "Capital Management Analyst (Banking)",
    variants: ["capital management analyst banking", "bank capital analyst", "regulatory capital analyst"],
    tags: ["treasury_balance_sheet"],
  },
  {
    industry: "banking",
    family: "finance",
    canonicalTitle: "Funding Manager (Banking)",
    variants: ["funding manager banking", "wholesale funding manager"],
    tags: ["treasury_balance_sheet"],
  },

  // ── Risk ─────────────────────────────────────────────────────────────────
  {
    industry: "banking",
    family: "risk",
    canonicalTitle: "Market Risk Analyst (Banking)",
    variants: ["market risk analyst banking", "bank market risk analyst"],
    tags: ["market_risk"],
  },
  {
    industry: "banking",
    family: "risk",
    canonicalTitle: "Market Risk Manager (Banking)",
    variants: ["market risk manager banking", "bank market risk manager"],
    tags: ["market_risk"],
  },
  {
    industry: "banking",
    family: "risk",
    canonicalTitle: "Counterparty Credit Risk Analyst",
    variants: ["ccr analyst"],
    tags: ["credit_risk"],
  },
  {
    industry: "banking",
    family: "risk",
    canonicalTitle: "Traded Risk Analyst",
    variants: ["traded risk manager"],
    tags: ["market_risk"],
  },
  {
    industry: "banking",
    family: "risk",
    canonicalTitle: "Risk Modelling Analyst (Banking)",
    variants: ["risk modelling analyst banking", "risk modeling analyst banking", "credit risk modelling analyst"],
    tags: ["risk_modelling"],
  },
  {
    industry: "banking",
    family: "risk",
    canonicalTitle: "Stress Testing Analyst",
    variants: ["stress testing manager"],
    tags: ["risk_modelling"],
  },
  {
    industry: "banking",
    family: "risk",
    canonicalTitle: "Enterprise Risk Manager (Banking)",
    variants: ["enterprise risk manager banking", "bank enterprise risk manager"],
    tags: [],
  },
  {
    industry: "banking",
    family: "risk",
    canonicalTitle: "Operational Risk Analyst (Banking)",
    variants: ["operational risk analyst banking", "bank operational risk analyst"],
    tags: [],
  },
  {
    industry: "banking",
    family: "risk",
    canonicalTitle: "Operational Risk Manager (Banking)",
    variants: ["operational risk manager banking", "bank operational risk manager"],
    tags: [],
  },
  {
    industry: "banking",
    family: "risk",
    canonicalTitle: "Quantitative Analyst (Banking)",
    variants: ["quantitative analyst banking", "quant analyst banking", "bank quantitative analyst"],
    tags: ["quant"],
  },
  {
    industry: "banking",
    family: "risk",
    canonicalTitle: "Front Office Quant Analyst",
    variants: ["front office quantitative analyst"],
    tags: ["quant"],
  },
  {
    industry: "banking",
    family: "risk",
    canonicalTitle: "Risk Quant Analyst",
    variants: ["risk quantitative analyst"],
    tags: ["quant"],
  },
  {
    industry: "banking",
    family: "risk",
    canonicalTitle: "Model Validation Analyst (Banking)",
    variants: ["model validation analyst banking", "model validation quant"],
    tags: ["quant"],
  },

  // ── Compliance & financial crime ─────────────────────────────────────────
  {
    industry: "banking",
    family: "compliance",
    canonicalTitle: "Compliance Analyst (Banking)",
    variants: ["compliance analyst banking", "banking compliance analyst"],
    tags: ["compliance_financial_crime"],
  },
  {
    industry: "banking",
    family: "compliance",
    canonicalTitle: "Compliance Manager (Banking)",
    variants: ["compliance manager banking", "banking compliance manager"],
    tags: ["compliance_financial_crime"],
  },
  {
    industry: "banking",
    family: "compliance",
    canonicalTitle: "Regulatory Compliance Manager (Banking)",
    variants: ["regulatory compliance manager banking"],
    tags: ["compliance_financial_crime"],
  },
  {
    industry: "banking",
    family: "compliance",
    canonicalTitle: "Financial Crime Analyst (Banking)",
    variants: ["financial crime analyst banking", "financial crime analyst"],
    tags: ["compliance_financial_crime"],
  },
  {
    industry: "banking",
    family: "compliance",
    canonicalTitle: "Financial Crime Manager (Banking)",
    variants: ["financial crime manager banking", "financial crime manager"],
    tags: ["compliance_financial_crime"],
  },
  {
    industry: "banking",
    family: "compliance",
    canonicalTitle: "AML Analyst",
    variants: ["anti money laundering analyst", "aml investigator", "anti money laundering investigator"],
    tags: ["compliance_financial_crime"],
  },
  {
    industry: "banking",
    family: "compliance",
    canonicalTitle: "Sanctions Screening Analyst (Banking)",
    variants: ["sanctions screening analyst banking", "sanctions analyst banking"],
    tags: ["compliance_financial_crime"],
  },
  {
    industry: "banking",
    family: "compliance",
    canonicalTitle: "KYC Analyst",
    variants: ["know your customer analyst", "kyc officer", "know your customer officer"],
    tags: ["compliance_financial_crime"],
  },
  {
    industry: "banking",
    family: "compliance",
    canonicalTitle: "Onboarding Analyst (Banking)",
    variants: ["onboarding analyst banking", "client onboarding analyst banking"],
    tags: ["compliance_financial_crime"],
  },
  {
    industry: "banking",
    family: "compliance",
    canonicalTitle: "Client Onboarding Specialist (Banking)",
    variants: ["client onboarding specialist banking"],
    tags: ["compliance_financial_crime"],
  },
  {
    industry: "banking",
    family: "compliance",
    canonicalTitle: "Internal Auditor (Banking)",
    variants: ["internal auditor banking", "bank internal auditor"],
    tags: ["internal_audit"],
  },
  {
    industry: "banking",
    family: "compliance",
    canonicalTitle: "Senior Internal Auditor (Banking)",
    variants: ["senior internal auditor banking"],
    seniority: "senior",
    tags: ["internal_audit"],
  },
  {
    industry: "banking",
    family: "compliance",
    canonicalTitle: "Audit Manager (Banking)",
    variants: ["audit manager banking", "internal audit manager banking"],
    tags: ["internal_audit"],
  },

  // ── Payments & transaction banking ───────────────────────────────────────
  {
    industry: "banking",
    family: "operations",
    canonicalTitle: "Payments Product Manager",
    variants: ["payments product manager bank", "payments product owner"],
    tags: ["payments_transaction_banking"],
  },
  {
    industry: "banking",
    family: "operations",
    canonicalTitle: "Payments Operations Manager",
    variants: ["payment operations manager"],
    tags: ["payments_transaction_banking"],
  },
  {
    industry: "banking",
    family: "operations",
    canonicalTitle: "Payments Analyst (Banking)",
    variants: ["payments analyst banking", "payments analyst"],
    tags: ["payments_transaction_banking"],
  },
  {
    industry: "banking",
    family: "operations",
    canonicalTitle: "Cards Product Manager",
    variants: ["card product manager", "credit cards product manager"],
    tags: ["payments_transaction_banking"],
  },
  {
    industry: "banking",
    family: "operations",
    canonicalTitle: "Cards Operations Manager",
    variants: ["card operations manager"],
    tags: ["payments_transaction_banking"],
  },
  {
    industry: "banking",
    family: "operations",
    canonicalTitle: "Trade Finance Officer",
    variants: ["trade finance analyst", "trade finance manager", "trade finance specialist"],
    tags: ["payments_transaction_banking"],
  },
  {
    industry: "banking",
    family: "operations",
    canonicalTitle: "Cash Management Specialist",
    variants: ["cash management officer banking"],
    tags: ["payments_transaction_banking"],
  },
  {
    industry: "banking",
    family: "operations",
    canonicalTitle: "Transaction Banking Specialist",
    variants: ["transaction banking manager", "transaction banking analyst"],
    tags: ["payments_transaction_banking"],
  },

  // ── Operations / middle & back office ────────────────────────────────────
  {
    industry: "banking",
    family: "operations",
    canonicalTitle: "Operations Analyst (Banking)",
    variants: ["operations analyst banking", "banking operations analyst"],
    tags: ["operations_middle_back_office"],
  },
  {
    industry: "banking",
    family: "operations",
    canonicalTitle: "Operations Manager (Banking)",
    variants: ["operations manager banking", "banking operations manager"],
    tags: ["operations_middle_back_office"],
  },
  {
    industry: "banking",
    family: "operations",
    canonicalTitle: "Middle Office Analyst (Banking)",
    variants: ["middle office analyst banking"],
    tags: ["operations_middle_back_office"],
  },
  {
    industry: "banking",
    family: "operations",
    canonicalTitle: "Settlements Analyst (Banking)",
    variants: ["settlements analyst banking", "settlement analyst banking"],
    tags: ["operations_middle_back_office"],
  },
  {
    industry: "banking",
    family: "operations",
    canonicalTitle: "Reconciliations Analyst (Banking)",
    variants: ["reconciliations analyst banking", "reconciliation analyst banking"],
    tags: ["operations_middle_back_office"],
  },
  {
    industry: "banking",
    family: "client_service",
    canonicalTitle: "Client Services Officer (Banking)",
    variants: ["client services officer banking", "client service officer banking"],
    tags: ["operations_middle_back_office"],
  },
  {
    industry: "banking",
    family: "operations",
    canonicalTitle: "Loan Operations Analyst",
    variants: ["loans operations analyst", "loan servicing analyst"],
    tags: ["operations_middle_back_office"],
  },
  {
    industry: "banking",
    family: "operations",
    canonicalTitle: "Trade Support Analyst (Banking)",
    variants: ["trade support analyst banking"],
    tags: ["operations_middle_back_office"],
  },
  {
    industry: "banking",
    family: "operations",
    canonicalTitle: "Collateral Management Analyst (Banking)",
    variants: ["collateral management analyst banking", "collateral analyst banking"],
    tags: ["operations_middle_back_office"],
  },

  // ── Digital, product & change ────────────────────────────────────────────
  {
    industry: "banking",
    family: "operations",
    canonicalTitle: "Digital Product Manager (Banking)",
    variants: ["digital product manager banking", "digital banking product manager"],
    tags: ["digital_product_change"],
  },
  {
    industry: "banking",
    family: "operations",
    canonicalTitle: "Digital Banking Product Owner",
    variants: ["digital banking po"],
    tags: ["digital_product_change"],
  },
  {
    industry: "banking",
    family: "operations",
    canonicalTitle: "Digital Transformation Manager (Banking)",
    variants: ["digital transformation manager banking"],
    tags: ["digital_product_change"],
  },
  {
    industry: "banking",
    family: "operations",
    canonicalTitle: "Business Analyst (Banking)",
    variants: ["business analyst banking", "banking business analyst"],
    tags: ["digital_product_change"],
  },
  {
    industry: "banking",
    family: "operations",
    canonicalTitle: "Change Manager (Banking)",
    variants: ["change manager banking", "banking change manager"],
    tags: ["digital_product_change"],
  },
  {
    industry: "banking",
    family: "operations",
    canonicalTitle: "Implementation Manager (Banking)",
    variants: ["implementation manager banking"],
    tags: ["digital_product_change"],
  },
  {
    industry: "banking",
    family: "operations",
    canonicalTitle: "Banking Technology Consultant",
    variants: ["banking technology analyst"],
    tags: ["digital_product_change"],
  },
  {
    industry: "banking",
    family: "operations",
    canonicalTitle: "Core Banking Systems Analyst",
    variants: ["core banking analyst"],
    tags: ["digital_product_change"],
  },
  {
    industry: "banking",
    family: "operations",
    canonicalTitle: "Payments Systems Analyst",
    variants: ["payment systems analyst"],
    tags: ["digital_product_change", "payments_transaction_banking"],
  },

  // ── Contact centre & collections ─────────────────────────────────────────
  {
    industry: "banking",
    family: "client_service",
    canonicalTitle: "Contact Centre Agent (Banking)",
    variants: ["contact centre agent banking", "banking contact centre agent", "call centre agent banking"],
    tags: ["contact_centre_collections"],
  },
  {
    industry: "banking",
    family: "client_service",
    canonicalTitle: "Contact Centre Team Leader (Banking)",
    variants: ["contact centre team leader banking"],
    tags: ["contact_centre_collections"],
  },
  {
    industry: "banking",
    family: "client_service",
    canonicalTitle: "Collections Agent (Banking)",
    variants: ["collections agent banking", "collections advisor banking"],
    tags: ["contact_centre_collections"],
  },
  {
    industry: "banking",
    family: "client_service",
    canonicalTitle: "Collections Manager (Banking)",
    variants: ["collections manager banking"],
    tags: ["contact_centre_collections"],
  },
  {
    industry: "banking",
    family: "client_service",
    canonicalTitle: "Recoveries Officer (Banking)",
    variants: ["recoveries officer banking", "recoveries specialist banking"],
    tags: ["contact_centre_collections"],
  },
];
