import type { CuratedTitleEntry } from "./types";

/**
 * Curated fund-manager (buy-side asset management) job titles — core
 * portfolio management, research, trading, distribution, risk/performance,
 * compliance/operations, and product/marketing roles.
 *
 * Real-assets / infrastructure / institutional-platform titles live in
 * assetManagementRealAssets.ts (same industry tag: "asset_management").
 * Overlapping titles between the two supplied lists are defined ONCE, here,
 * with the other list's phrasing as variants.
 *
 * FALSE-POSITIVE RULE: titles that also exist outside asset management
 * (e.g. "Performance Analyst" in sports/marketing, "Valuations Analyst" in
 * property, "Head of Research" anywhere) are only included with an
 * investment/fund qualifier. Single-word variants only match exactly.
 *
 * PASTE ADDITIONAL TITLES HERE following the same shape.
 */
export const FUND_MANAGER_TITLES: CuratedTitleEntry[] = [
  // ── Executive leadership ─────────────────────────────────────────────────
  {
    industry: "asset_management",
    family: "operations",
    canonicalTitle: "Chief Executive Officer (Asset Management)",
    variants: ["chief executive officer asset management", "asset management ceo"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Chief Investment Officer (Fund Manager)",
    variants: ["chief investment officer fund manager", "chief investment officer asset management", "cio asset management"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Deputy Chief Investment Officer",
    variants: ["deputy cio asset management"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Head of Investments",
    variants: ["investments director"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Head of Equities",
    variants: ["equities director"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Head of Fixed Income",
    variants: ["fixed income director"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Head of Multi-Asset",
    variants: ["head of multi asset", "multi asset director"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Head of Alternatives",
    variants: ["head of alternatives asset management", "alternatives director"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Head of ESG Investing",
    variants: ["head of esg asset management", "head of responsible investment", "esg investing director"],
    seniority: "executive",
    tags: ["executive_leadership", "esg"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Head of Investment Research",
    variants: ["head of research asset management", "investment research director"],
    seniority: "executive",
    tags: ["executive_leadership", "research_analysis"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Head of Portfolio Management",
    variants: ["portfolio management director"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Head of Trading (Asset Management)",
    variants: ["head of trading asset management", "head of dealing", "head of buy side trading"],
    seniority: "executive",
    tags: ["executive_leadership", "trading_dealing"],
  },
  {
    industry: "asset_management",
    family: "client_service",
    canonicalTitle: "Head of Distribution (Asset Management)",
    variants: ["head of distribution asset management", "distribution director asset management"],
    seniority: "executive",
    tags: ["executive_leadership", "client_sales_distribution"],
  },
  {
    industry: "asset_management",
    family: "client_service",
    canonicalTitle: "Head of Institutional Sales",
    variants: ["institutional sales director"],
    seniority: "executive",
    tags: ["executive_leadership", "client_sales_distribution"],
  },
  {
    industry: "asset_management",
    family: "client_service",
    canonicalTitle: "Head of Wholesale Sales",
    variants: ["wholesale distribution director"],
    seniority: "executive",
    tags: ["executive_leadership", "client_sales_distribution"],
  },

  // ── Portfolio management ─────────────────────────────────────────────────
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Portfolio Manager",
    variants: ["co portfolio manager", "lead portfolio manager"],
    tags: ["portfolio_management"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Senior Portfolio Manager",
    variants: [],
    seniority: "senior",
    tags: ["portfolio_management"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Assistant Portfolio Manager",
    variants: ["associate portfolio manager"],
    seniority: "junior",
    tags: ["portfolio_management"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Multi-Asset Portfolio Manager",
    variants: ["multi asset portfolio manager", "multi asset fund manager"],
    tags: ["portfolio_management"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Equity Portfolio Manager",
    variants: ["equities portfolio manager", "equity fund manager"],
    tags: ["portfolio_management"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Fixed Income Portfolio Manager",
    variants: ["fixed income fund manager", "bond portfolio manager", "bond fund manager"],
    tags: ["portfolio_management"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Credit Portfolio Manager",
    variants: ["credit fund manager"],
    tags: ["portfolio_management"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "High Yield Portfolio Manager",
    variants: ["high yield fund manager"],
    tags: ["portfolio_management"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Emerging Markets Portfolio Manager",
    variants: ["emerging markets fund manager", "em portfolio manager"],
    tags: ["portfolio_management"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Absolute Return Portfolio Manager",
    variants: ["absolute return fund manager"],
    tags: ["portfolio_management"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Quant Portfolio Manager",
    variants: ["quantitative portfolio manager", "systematic portfolio manager"],
    tags: ["portfolio_management", "quant"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Index Portfolio Manager",
    variants: ["passive portfolio manager", "index fund manager"],
    tags: ["portfolio_management"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "ETF Portfolio Manager",
    variants: ["etf fund manager"],
    tags: ["portfolio_management"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Fund Manager",
    variants: ["investment manager fund management"],
    tags: ["portfolio_management"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Fund of Funds Manager",
    variants: ["fund of funds portfolio manager", "multi manager portfolio manager"],
    tags: ["portfolio_management"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Assistant Fund Manager",
    variants: ["junior fund manager", "trainee fund manager"],
    seniority: "junior",
    tags: ["portfolio_management"],
  },

  // ── Research & analysis ──────────────────────────────────────────────────
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Investment Analyst",
    variants: ["investments analyst"],
    tags: ["research_analysis"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Equity Research Analyst (Buy-Side)",
    variants: ["buy side equity research analyst", "equity research analyst buy side", "buy side equity analyst"],
    tags: ["research_analysis"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Credit Research Analyst (Buy-Side)",
    variants: ["buy side credit research analyst", "credit research analyst buy side", "buy side credit analyst"],
    tags: ["research_analysis"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Fixed Income Analyst (Buy-Side)",
    variants: ["buy side fixed income analyst", "fixed income analyst buy side", "fixed income research analyst"],
    tags: ["research_analysis"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Multi-Asset Analyst",
    variants: ["multi asset analyst", "multi asset research analyst"],
    tags: ["research_analysis"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Fund Research Analyst",
    variants: ["funds research analyst"],
    tags: ["research_analysis"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Manager Research Analyst",
    variants: ["manager selection analyst"],
    tags: ["research_analysis"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Quantitative Research Analyst (Asset Management)",
    variants: ["quantitative research analyst asset management", "quant research analyst asset management", "quant researcher buy side"],
    tags: ["research_analysis", "quant"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "ESG Analyst",
    variants: ["esg research analyst", "esg investment analyst", "sri analyst", "sustainable investment analyst"],
    tags: ["research_analysis", "esg"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Thematic Investment Analyst",
    variants: ["thematic research analyst"],
    tags: ["research_analysis"],
  },

  // ── Trading & dealing ────────────────────────────────────────────────────
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Trader (Asset Management)",
    variants: ["trader asset management", "buy side trader"],
    tags: ["trading_dealing"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Equity Trader (Buy-Side)",
    variants: ["buy side equity trader", "equity trader buy side", "equity dealer"],
    tags: ["trading_dealing"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Fixed Income Trader (Buy-Side)",
    variants: ["buy side fixed income trader", "fixed income trader buy side", "fixed income dealer", "bond dealer"],
    tags: ["trading_dealing"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "FX Trader (Buy-Side)",
    variants: ["buy side fx trader", "fx trader buy side", "fx dealer"],
    tags: ["trading_dealing"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Derivatives Trader (Buy-Side)",
    variants: ["buy side derivatives trader", "derivatives trader buy side", "derivatives dealer"],
    tags: ["trading_dealing"],
  },
  {
    industry: "asset_management",
    family: "investments",
    canonicalTitle: "Execution Trader",
    variants: ["execution dealer"],
    tags: ["trading_dealing"],
  },
  {
    industry: "asset_management",
    family: "operations",
    canonicalTitle: "Dealing Desk Analyst",
    variants: ["dealing desk assistant", "dealing analyst"],
    tags: ["trading_dealing"],
  },

  // ── Client, sales & distribution ─────────────────────────────────────────
  {
    industry: "asset_management",
    family: "client_service",
    canonicalTitle: "Client Portfolio Manager",
    variants: ["cpm asset management"],
    tags: ["client_sales_distribution"],
  },
  {
    industry: "asset_management",
    family: "client_service",
    canonicalTitle: "Investment Specialist",
    variants: ["investment product specialist"],
    tags: ["client_sales_distribution"],
  },
  {
    industry: "asset_management",
    family: "client_service",
    canonicalTitle: "Product Specialist (Asset Management)",
    variants: ["product specialist asset management", "fund product specialist"],
    tags: ["client_sales_distribution"],
  },
  {
    industry: "asset_management",
    family: "client_service",
    canonicalTitle: "Client Director (Asset Management)",
    variants: ["client director asset management", "institutional client director"],
    tags: ["client_sales_distribution"],
  },
  {
    industry: "asset_management",
    family: "client_service",
    canonicalTitle: "Wholesale Sales Manager (Asset Management)",
    variants: ["wholesale sales manager asset management", "wholesale distribution manager"],
    tags: ["client_sales_distribution"],
  },
  {
    industry: "asset_management",
    family: "client_service",
    canonicalTitle: "Sales Director (Asset Management)",
    variants: ["sales director asset management", "distribution sales director"],
    seniority: "senior",
    tags: ["client_sales_distribution"],
  },
  {
    industry: "asset_management",
    family: "client_service",
    canonicalTitle: "Business Development Manager (Asset Management)",
    variants: ["business development manager asset management", "bdm asset management"],
    tags: ["client_sales_distribution"],
  },
  {
    industry: "asset_management",
    family: "client_service",
    canonicalTitle: "Client Relationship Manager (Asset Management)",
    variants: ["client relationship manager asset management", "relationship manager asset management"],
    tags: ["client_sales_distribution"],
  },
  {
    industry: "asset_management",
    family: "client_service",
    canonicalTitle: "Client Service Manager (Asset Management)",
    variants: ["client service manager asset management", "client services manager asset management"],
    tags: ["client_sales_distribution"],
  },
  {
    industry: "asset_management",
    family: "client_service",
    canonicalTitle: "Client Reporting Analyst",
    variants: ["client reporting specialist"],
    tags: ["client_sales_distribution"],
  },
  {
    industry: "asset_management",
    family: "client_service",
    canonicalTitle: "RFP Writer (Asset Management)",
    variants: ["rfp writer asset management", "rfp writer institutional", "rfp specialist asset management", "rfp manager asset management"],
    tags: ["client_sales_distribution"],
  },
  {
    industry: "asset_management",
    family: "client_service",
    canonicalTitle: "Consultant Relations Manager",
    variants: ["consultant relations associate"],
    tags: ["client_sales_distribution"],
  },

  // ── Risk & performance ───────────────────────────────────────────────────
  {
    industry: "asset_management",
    family: "risk",
    canonicalTitle: "Risk Analyst (Asset Management)",
    variants: ["risk analyst asset management"],
    tags: ["risk_performance"],
  },
  {
    industry: "asset_management",
    family: "risk",
    canonicalTitle: "Investment Risk Analyst",
    variants: ["investment risk associate"],
    tags: ["risk_performance"],
  },
  {
    industry: "asset_management",
    family: "risk",
    canonicalTitle: "Portfolio Risk Analyst",
    variants: [],
    tags: ["risk_performance"],
  },
  {
    industry: "asset_management",
    family: "risk",
    canonicalTitle: "Market Risk Manager (Asset Management)",
    variants: ["market risk manager asset management", "market risk analyst asset management"],
    tags: ["risk_performance"],
  },
  {
    industry: "asset_management",
    family: "risk",
    canonicalTitle: "Performance Analyst (Investments)",
    variants: ["investment performance analyst", "fund performance analyst", "performance analyst asset management", "performance measurement analyst"],
    tags: ["risk_performance"],
  },
  {
    industry: "asset_management",
    family: "risk",
    canonicalTitle: "Senior Performance Analyst (Investments)",
    variants: ["senior investment performance analyst", "senior fund performance analyst"],
    seniority: "senior",
    tags: ["risk_performance"],
  },
  {
    industry: "asset_management",
    family: "risk",
    canonicalTitle: "Attribution Analyst",
    variants: ["performance attribution analyst"],
    tags: ["risk_performance"],
  },
  {
    industry: "asset_management",
    family: "risk",
    canonicalTitle: "Performance and Risk Analyst",
    variants: ["performance & risk analyst", "risk and performance analyst"],
    tags: ["risk_performance"],
  },

  // ── Compliance & operations ──────────────────────────────────────────────
  {
    industry: "asset_management",
    family: "compliance",
    canonicalTitle: "Compliance Officer (Asset Management)",
    variants: ["compliance officer asset management", "compliance analyst asset management"],
    tags: ["compliance_operations"],
  },
  {
    industry: "asset_management",
    family: "compliance",
    canonicalTitle: "Compliance Manager (Asset Management)",
    variants: ["compliance manager asset management"],
    tags: ["compliance_operations"],
  },
  {
    industry: "asset_management",
    family: "compliance",
    canonicalTitle: "Regulatory Reporting Specialist (Funds)",
    variants: ["regulatory reporting specialist funds", "fund regulatory reporting analyst"],
    tags: ["compliance_operations"],
  },
  {
    industry: "asset_management",
    family: "compliance",
    canonicalTitle: "AML Analyst (Asset Management)",
    variants: ["aml analyst asset management", "financial crime analyst asset management"],
    tags: ["compliance_operations"],
  },
  {
    industry: "asset_management",
    family: "operations",
    canonicalTitle: "Operations Analyst (Asset Management)",
    variants: ["operations analyst asset management", "investment operations analyst"],
    tags: ["compliance_operations"],
  },
  {
    industry: "asset_management",
    family: "operations",
    canonicalTitle: "Fund Operations Manager",
    variants: ["fund operations specialist", "funds operations manager"],
    tags: ["compliance_operations"],
  },
  {
    industry: "asset_management",
    family: "operations",
    canonicalTitle: "Middle Office Analyst (Asset Management)",
    variants: ["middle office analyst asset management"],
    tags: ["compliance_operations"],
  },
  {
    industry: "asset_management",
    family: "operations",
    canonicalTitle: "Trade Support Analyst (Asset Management)",
    variants: ["trade support analyst asset management"],
    tags: ["compliance_operations"],
  },
  {
    industry: "asset_management",
    family: "operations",
    canonicalTitle: "Settlements Analyst (Asset Management)",
    variants: ["settlements analyst asset management"],
    tags: ["compliance_operations"],
  },
  {
    industry: "asset_management",
    family: "operations",
    canonicalTitle: "Reconciliations Analyst (Asset Management)",
    variants: ["reconciliations analyst asset management"],
    tags: ["compliance_operations"],
  },
  {
    industry: "asset_management",
    family: "finance",
    canonicalTitle: "Valuations Analyst (Funds)",
    variants: ["fund valuations analyst", "valuations analyst funds", "fund valuation analyst"],
    tags: ["compliance_operations"],
  },
  {
    industry: "asset_management",
    family: "finance",
    canonicalTitle: "Fund Accountant",
    variants: ["funds accountant", "fund accounting analyst"],
    tags: ["compliance_operations"],
  },
  {
    industry: "asset_management",
    family: "finance",
    canonicalTitle: "Senior Fund Accountant",
    variants: ["senior funds accountant"],
    seniority: "senior",
    tags: ["compliance_operations"],
  },
  {
    industry: "asset_management",
    family: "finance",
    canonicalTitle: "NAV Specialist",
    variants: ["nav analyst", "net asset value specialist", "nav oversight analyst"],
    tags: ["compliance_operations"],
  },
  {
    industry: "asset_management",
    family: "finance",
    canonicalTitle: "Pricing Analyst (Funds)",
    variants: ["pricing analyst funds", "fund pricing analyst"],
    tags: ["compliance_operations"],
  },

  // ── Product & marketing ──────────────────────────────────────────────────
  {
    industry: "asset_management",
    family: "client_service",
    canonicalTitle: "Product Manager (Asset Management)",
    variants: ["product manager asset management", "fund product manager"],
    tags: ["product_marketing"],
  },
  {
    industry: "asset_management",
    family: "client_service",
    canonicalTitle: "Fund Launch Manager",
    variants: ["fund launch specialist"],
    tags: ["product_marketing"],
  },
  {
    industry: "asset_management",
    family: "client_service",
    canonicalTitle: "Product Development Manager (Funds)",
    variants: ["product development manager funds", "product development manager asset management", "fund product development manager"],
    tags: ["product_marketing"],
  },
  {
    industry: "asset_management",
    family: "client_service",
    canonicalTitle: "Product Governance Manager (Funds)",
    variants: ["product governance manager funds", "fund product governance manager"],
    tags: ["product_marketing"],
  },
  {
    industry: "asset_management",
    family: "client_service",
    canonicalTitle: "Marketing Manager (Asset Management)",
    variants: ["marketing manager asset management", "fund marketing manager"],
    tags: ["product_marketing"],
  },
  {
    industry: "asset_management",
    family: "client_service",
    canonicalTitle: "Content Marketing Specialist (Asset Management)",
    variants: ["content marketing specialist asset management", "investment content specialist"],
    tags: ["product_marketing"],
  },
  {
    industry: "asset_management",
    family: "client_service",
    canonicalTitle: "Investment Writer",
    variants: ["investment writer asset management", "investment copywriter"],
    tags: ["product_marketing"],
  },
];
