import type { CuratedTitleEntry } from "./types";

/**
 * Curated IT/Tech job titles ("it_tech" sector).
 *
 * Families use the tech FinFunctions added in finTaxonomy.ts
 * (software_engineering, cloud_infrastructure, devops_sre, data_engineering,
 * data_analytics, data_science_ml_ai, cyber_security, it_operations_service,
 * end_user_support, business_systems_analysis, product_management_tech,
 * project_delivery_agile, ux_design, quality_assurance, solutions_presales).
 * The spec's finer groupings (executive_leadership_tech, systems_network_admin,
 * networks_telecoms, database_administration, data_governance,
 * enterprise_apps_crm_erp, hardware_iot_robotics, games_interactive_media,
 * innovation_rnd_tech, training_documentation) live in `tags`.
 *
 * FALSE-POSITIVE NOTES (collision guards, same pattern as the other files):
 *  - Bare "Business Analyst" is deliberately NOT ingested — it stays
 *    ambiguous (banking claims "Business Analyst (Banking)", finance claims
 *    "Business Analyst (Finance)"). Only IT-qualified forms are curated:
 *    "IT/Digital/Technical Business Analyst", "Business Systems Analyst".
 *  - Bare "Project Manager" / "Programme Manager" / "Product Manager" are NOT
 *    claimed — only tech-qualified forms.
 *  - Bare "Implementation Consultant/Manager/Specialist" are NOT claimed
 *    (pensions vocabulary) — only technology-qualified forms.
 *  - Bare "Business Partner" stays unclaimed; "IT Business Partner" is curated.
 *
 * PASTE ADDITIONAL TITLES HERE following the same shape.
 */
export const IT_TECH_TITLES: CuratedTitleEntry[] = [
  // ── Executive leadership ─────────────────────────────────────────────────
  {
    industry: "it_tech",
    family: "it_operations_service",
    canonicalTitle: "Chief Information Officer",
    variants: ["cio", "group chief information officer"],
    seniority: "executive",
    tags: ["executive_leadership_tech"],
  },
  {
    industry: "it_tech",
    family: "software_engineering",
    canonicalTitle: "Chief Technology Officer",
    variants: ["cto", "group chief technology officer"],
    seniority: "executive",
    tags: ["executive_leadership_tech"],
  },
  {
    industry: "it_tech",
    family: "it_operations_service",
    canonicalTitle: "Chief Digital Officer",
    variants: ["chief digital and information officer"],
    seniority: "executive",
    tags: ["executive_leadership_tech", "innovation_rnd_tech"],
  },
  {
    industry: "it_tech",
    family: "data_engineering",
    canonicalTitle: "Chief Data Officer",
    variants: ["group chief data officer"],
    seniority: "executive",
    tags: ["executive_leadership_tech", "data_governance"],
  },
  {
    industry: "it_tech",
    family: "cyber_security",
    canonicalTitle: "Chief Information Security Officer",
    variants: ["ciso", "group chief information security officer"],
    seniority: "executive",
    tags: ["executive_leadership_tech"],
  },
  {
    industry: "it_tech",
    family: "product_management_tech",
    canonicalTitle: "Chief Product Officer (Technology)",
    variants: ["chief product officer technology", "chief product and technology officer"],
    seniority: "executive",
    tags: ["executive_leadership_tech"],
  },
  {
    industry: "it_tech",
    family: "data_analytics",
    canonicalTitle: "Chief Analytics Officer",
    variants: ["group chief analytics officer"],
    seniority: "executive",
    tags: ["executive_leadership_tech"],
  },
  {
    industry: "it_tech",
    family: "software_engineering",
    canonicalTitle: "VP Engineering",
    variants: ["vp of engineering", "vice president of engineering", "vice president engineering"],
    seniority: "executive",
    tags: ["executive_leadership_tech"],
  },
  {
    industry: "it_tech",
    family: "it_operations_service",
    canonicalTitle: "VP Technology",
    variants: ["vp of technology", "vp it", "vp information technology"],
    seniority: "executive",
    tags: ["executive_leadership_tech"],
  },
  {
    industry: "it_tech",
    family: "product_management_tech",
    canonicalTitle: "VP Product (Technology)",
    variants: ["vp product technology", "vp of product technology"],
    seniority: "executive",
    tags: ["executive_leadership_tech"],
  },
  {
    industry: "it_tech",
    family: "data_science_ml_ai",
    canonicalTitle: "VP Data Science",
    variants: ["vp of data science", "vice president data science"],
    seniority: "executive",
    tags: ["executive_leadership_tech"],
  },
  {
    industry: "it_tech",
    family: "software_engineering",
    canonicalTitle: "Head of Engineering",
    variants: [
      "head of software development",
      "head of software engineering",
      "head of engineering platform",
      "head of engineering product",
    ],
    seniority: "executive",
    tags: ["executive_leadership_tech"],
  },
  {
    industry: "it_tech",
    family: "it_operations_service",
    canonicalTitle: "Head of Technology",
    variants: ["head of it", "head of information technology"],
    seniority: "executive",
    tags: ["executive_leadership_tech"],
  },
  {
    industry: "it_tech",
    family: "data_engineering",
    canonicalTitle: "Head of Data",
    variants: ["head of data engineering"],
    seniority: "executive",
    tags: ["executive_leadership_tech", "data_governance"],
  },
  {
    industry: "it_tech",
    family: "cyber_security",
    canonicalTitle: "Head of Cyber Security",
    variants: ["head of cyber defence", "head of information security", "head of cybersecurity"],
    seniority: "executive",
    tags: ["executive_leadership_tech"],
  },
  {
    industry: "it_tech",
    family: "cloud_infrastructure",
    canonicalTitle: "Head of Infrastructure",
    variants: ["head of infrastructure cloud", "head of it infrastructure"],
    seniority: "executive",
    tags: ["executive_leadership_tech"],
  },
  {
    industry: "it_tech",
    family: "devops_sre",
    canonicalTitle: "Head of DevOps",
    variants: ["head of devops engineering"],
    seniority: "executive",
    tags: ["executive_leadership_tech"],
  },
  {
    industry: "it_tech",
    family: "software_engineering",
    canonicalTitle: "Head of Architecture",
    variants: ["head of architecture technology", "head of enterprise architecture"],
    seniority: "executive",
    tags: ["executive_leadership_tech"],
  },
  {
    industry: "it_tech",
    family: "product_management_tech",
    canonicalTitle: "Head of Product (Tech)",
    variants: ["head of product technology", "head of product tech"],
    seniority: "executive",
    tags: ["executive_leadership_tech"],
  },
  {
    industry: "it_tech",
    family: "ux_design",
    canonicalTitle: "Head of UX",
    variants: ["head of user experience", "head of ux design"],
    seniority: "executive",
    tags: ["executive_leadership_tech"],
  },
  {
    industry: "it_tech",
    family: "data_science_ml_ai",
    canonicalTitle: "Head of Data Science",
    variants: ["head of machine learning"],
    seniority: "executive",
    tags: ["executive_leadership_tech"],
  },
  {
    industry: "it_tech",
    family: "data_science_ml_ai",
    canonicalTitle: "Head of AI",
    variants: ["head of artificial intelligence"],
    seniority: "executive",
    tags: ["executive_leadership_tech"],
  },
  // ── Directors ────────────────────────────────────────────────────────────
  {
    industry: "it_tech",
    family: "it_operations_service",
    canonicalTitle: "IT Director",
    variants: ["technology director", "director of technology", "director of it"],
    seniority: "executive",
    tags: ["executive_leadership_tech"],
  },
  {
    industry: "it_tech",
    family: "software_engineering",
    canonicalTitle: "Director of Software Engineering",
    variants: ["director of engineering", "director of platform engineering", "software engineering director"],
    seniority: "executive",
    tags: ["executive_leadership_tech"],
  },
  {
    industry: "it_tech",
    family: "cloud_infrastructure",
    canonicalTitle: "Director of Infrastructure",
    variants: ["director of cloud engineering", "infrastructure director"],
    seniority: "executive",
    tags: ["executive_leadership_tech"],
  },
  {
    industry: "it_tech",
    family: "data_engineering",
    canonicalTitle: "Director of Data Engineering",
    variants: ["data engineering director"],
    seniority: "executive",
    tags: ["executive_leadership_tech"],
  },
  {
    industry: "it_tech",
    family: "cyber_security",
    canonicalTitle: "Director of Information Security",
    variants: ["director of cyber security", "information security director", "cyber security director"],
    seniority: "executive",
    tags: ["executive_leadership_tech"],
  },
  {
    industry: "it_tech",
    family: "software_engineering",
    canonicalTitle: "Director of Enterprise Architecture",
    variants: ["enterprise architecture director"],
    seniority: "executive",
    tags: ["executive_leadership_tech"],
  },
  {
    industry: "it_tech",
    family: "product_management_tech",
    canonicalTitle: "Director of Product Management (Tech)",
    variants: ["director of product management tech", "director of product management technology"],
    seniority: "executive",
    tags: ["executive_leadership_tech"],
  },
  {
    industry: "it_tech",
    family: "it_operations_service",
    canonicalTitle: "Director of IT Operations",
    variants: ["director of it service delivery", "it operations director"],
    seniority: "executive",
    tags: ["executive_leadership_tech"],
  },
  // ── Software engineering / development ──────────────────────────────────
  {
    industry: "it_tech",
    family: "software_engineering",
    canonicalTitle: "Software Engineer",
    variants: [
      "software developer",
      "application developer",
      "applications engineer",
      "desktop application developer",
      "systems software engineer",
    ],
  },
  {
    industry: "it_tech",
    family: "software_engineering",
    canonicalTitle: "Backend Engineer",
    variants: ["backend developer", "back end engineer", "back end developer"],
  },
  {
    industry: "it_tech",
    family: "software_engineering",
    canonicalTitle: "Frontend Engineer",
    variants: ["frontend developer", "front end engineer", "front end developer"],
  },
  {
    industry: "it_tech",
    family: "software_engineering",
    canonicalTitle: "Full Stack Engineer",
    variants: ["full stack developer", "fullstack engineer", "fullstack developer"],
  },
  {
    industry: "it_tech",
    family: "software_engineering",
    canonicalTitle: "Web Developer",
    variants: ["web engineer"],
  },
  {
    industry: "it_tech",
    family: "software_engineering",
    canonicalTitle: "UI Engineer",
    variants: ["ux engineer"],
  },
  {
    industry: "it_tech",
    family: "software_engineering",
    canonicalTitle: "Mobile Developer",
    variants: ["mobile engineer", "mobile application developer"],
  },
  {
    industry: "it_tech",
    family: "software_engineering",
    canonicalTitle: "iOS Developer",
    variants: ["ios engineer"],
  },
  {
    industry: "it_tech",
    family: "software_engineering",
    canonicalTitle: "Android Developer",
    variants: ["android engineer"],
  },
  {
    industry: "it_tech",
    family: "software_engineering",
    canonicalTitle: "Embedded Software Engineer",
    variants: ["embedded systems engineer", "firmware engineer"],
    tags: ["hardware_iot_robotics"],
  },
  {
    industry: "it_tech",
    family: "software_engineering",
    canonicalTitle: "Game Developer",
    variants: ["game programmer", "games developer", "games programmer"],
    tags: ["games_interactive_media"],
  },
  {
    industry: "it_tech",
    family: "software_engineering",
    canonicalTitle: "Graphics Engineer",
    variants: ["graphics programmer"],
    tags: ["games_interactive_media"],
  },
  {
    industry: "it_tech",
    family: "software_engineering",
    canonicalTitle: "Platform Engineer",
    variants: ["platform developer"],
  },
  {
    industry: "it_tech",
    family: "software_engineering",
    canonicalTitle: "Senior Software Engineer",
    variants: ["senior software developer"],
    seniority: "senior",
  },
  {
    industry: "it_tech",
    family: "software_engineering",
    canonicalTitle: "Lead Software Engineer",
    variants: ["principal software engineer", "staff software engineer", "lead developer"],
    seniority: "senior",
  },
  {
    industry: "it_tech",
    family: "software_engineering",
    canonicalTitle: "Software Architect",
    variants: ["applications architect"],
    seniority: "senior",
  },
  {
    industry: "it_tech",
    family: "software_engineering",
    canonicalTitle: "Solution Architect",
    variants: ["solutions architect"],
    seniority: "senior",
  },
  {
    industry: "it_tech",
    family: "software_engineering",
    canonicalTitle: "Enterprise Architect",
    variants: [],
    seniority: "senior",
  },
  {
    industry: "it_tech",
    family: "software_engineering",
    canonicalTitle: "System Architect",
    variants: ["systems architect"],
    seniority: "senior",
  },
  {
    industry: "it_tech",
    family: "software_engineering",
    canonicalTitle: "Technical Lead",
    variants: ["tech lead", "engineering lead"],
    seniority: "senior",
  },
  {
    industry: "it_tech",
    family: "software_engineering",
    canonicalTitle: "Engineering Manager",
    variants: [],
    seniority: "senior",
  },
  {
    industry: "it_tech",
    family: "software_engineering",
    canonicalTitle: "Software Development Manager",
    variants: ["agile development manager", "development manager software"],
    seniority: "senior",
  },
  {
    industry: "it_tech",
    family: "software_engineering",
    canonicalTitle: "Junior Software Engineer",
    variants: [
      "graduate software engineer",
      "junior developer",
      "junior software developer",
      "associate developer",
      "trainee developer",
    ],
    seniority: "junior",
  },
  // ── Cloud / infrastructure ───────────────────────────────────────────────
  {
    industry: "it_tech",
    family: "cloud_infrastructure",
    canonicalTitle: "Cloud Engineer",
    variants: ["cloud consultant"],
  },
  {
    industry: "it_tech",
    family: "cloud_infrastructure",
    canonicalTitle: "Cloud Architect",
    variants: ["cloud solutions architect"],
    seniority: "senior",
  },
  {
    industry: "it_tech",
    family: "cloud_infrastructure",
    canonicalTitle: "Cloud Infrastructure Engineer",
    variants: ["cloud platform engineer"],
  },
  {
    industry: "it_tech",
    family: "cloud_infrastructure",
    canonicalTitle: "Cloud Operations Engineer",
    variants: ["cloud systems administrator"],
    tags: ["systems_network_admin"],
  },
  // ── DevOps / SRE ─────────────────────────────────────────────────────────
  {
    industry: "it_tech",
    family: "devops_sre",
    canonicalTitle: "DevOps Engineer",
    variants: ["cloud devops engineer"],
  },
  {
    industry: "it_tech",
    family: "devops_sre",
    canonicalTitle: "Senior DevOps Engineer",
    variants: ["lead devops engineer"],
    seniority: "senior",
  },
  {
    industry: "it_tech",
    family: "devops_sre",
    canonicalTitle: "DevOps Manager",
    variants: [],
    seniority: "senior",
  },
  {
    industry: "it_tech",
    family: "devops_sre",
    canonicalTitle: "Site Reliability Engineer",
    variants: ["sre", "senior site reliability engineer", "platform reliability engineer"],
  },
  {
    industry: "it_tech",
    family: "devops_sre",
    canonicalTitle: "Build Engineer",
    variants: ["release engineer", "configuration engineer"],
  },
  {
    industry: "it_tech",
    family: "devops_sre",
    canonicalTitle: "Automation Engineer (DevOps)",
    variants: ["automation engineer devops", "devops automation engineer", "ci/cd engineer", "ci cd engineer"],
  },
  // ── Data engineering ─────────────────────────────────────────────────────
  {
    industry: "it_tech",
    family: "data_engineering",
    canonicalTitle: "Data Engineer",
    variants: ["big data engineer"],
  },
  {
    industry: "it_tech",
    family: "data_engineering",
    canonicalTitle: "Senior Data Engineer",
    variants: ["lead data engineer"],
    seniority: "senior",
  },
  {
    industry: "it_tech",
    family: "data_engineering",
    canonicalTitle: "ETL Engineer",
    variants: ["data pipeline engineer", "etl developer"],
  },
  {
    industry: "it_tech",
    family: "data_engineering",
    canonicalTitle: "Analytics Engineer",
    variants: ["bi engineer"],
  },
  {
    industry: "it_tech",
    family: "data_engineering",
    canonicalTitle: "Data Warehouse Engineer",
    variants: ["data warehouse developer"],
  },
  {
    industry: "it_tech",
    family: "data_engineering",
    canonicalTitle: "Database Engineer",
    variants: [],
    tags: ["database_administration"],
  },
  // ── Database administration / data governance ────────────────────────────
  {
    industry: "it_tech",
    family: "data_engineering",
    canonicalTitle: "Database Administrator",
    variants: ["dba", "senior database administrator"],
    tags: ["database_administration"],
  },
  {
    industry: "it_tech",
    family: "data_engineering",
    canonicalTitle: "Database Architect",
    variants: [],
    seniority: "senior",
    tags: ["database_administration"],
  },
  {
    industry: "it_tech",
    family: "data_engineering",
    canonicalTitle: "Data Quality Manager",
    variants: ["data steward"],
    tags: ["data_governance"],
  },
  // ── Data analysis ────────────────────────────────────────────────────────
  {
    industry: "it_tech",
    family: "data_analytics",
    canonicalTitle: "Data Analyst",
    variants: ["senior data analyst", "product data analyst", "marketing data analyst"],
  },
  {
    industry: "it_tech",
    family: "data_analytics",
    canonicalTitle: "Business Intelligence Analyst",
    variants: ["bi analyst", "business intelligence developer"],
  },
  {
    industry: "it_tech",
    family: "data_analytics",
    canonicalTitle: "Reporting Analyst",
    variants: [],
  },
  {
    industry: "it_tech",
    family: "data_analytics",
    canonicalTitle: "MI Analyst (IT)",
    variants: ["mi analyst it", "it mi analyst"],
  },
  // ── Data science / ML / AI ───────────────────────────────────────────────
  {
    industry: "it_tech",
    family: "data_science_ml_ai",
    canonicalTitle: "Data Scientist",
    variants: [],
  },
  {
    industry: "it_tech",
    family: "data_science_ml_ai",
    canonicalTitle: "Senior Data Scientist",
    variants: ["lead data scientist"],
    seniority: "senior",
  },
  {
    industry: "it_tech",
    family: "data_science_ml_ai",
    canonicalTitle: "Machine Learning Engineer",
    variants: ["ml engineer", "machine learning developer"],
  },
  {
    industry: "it_tech",
    family: "data_science_ml_ai",
    canonicalTitle: "AI Engineer",
    variants: ["nlp engineer", "computer vision engineer", "artificial intelligence engineer"],
  },
  {
    industry: "it_tech",
    family: "data_science_ml_ai",
    canonicalTitle: "Research Scientist (Machine Learning)",
    variants: ["research scientist machine learning", "machine learning research scientist", "machine learning scientist"],
  },
  {
    industry: "it_tech",
    family: "data_science_ml_ai",
    canonicalTitle: "Quantitative Developer (Tech)",
    variants: ["quantitative developer tech"],
  },
  {
    industry: "it_tech",
    family: "data_science_ml_ai",
    canonicalTitle: "Algorithm Engineer",
    variants: ["algorithms engineer"],
  },
  // ── Security / cyber / InfoSec ───────────────────────────────────────────
  {
    industry: "it_tech",
    family: "cyber_security",
    canonicalTitle: "Information Security Analyst",
    variants: ["cyber security analyst", "security analyst", "information assurance analyst"],
  },
  {
    industry: "it_tech",
    family: "cyber_security",
    canonicalTitle: "Security Engineer",
    variants: ["cyber security engineer", "information security engineer", "information assurance engineer"],
  },
  {
    industry: "it_tech",
    family: "cyber_security",
    canonicalTitle: "Senior Security Engineer",
    variants: ["lead security engineer"],
    seniority: "senior",
  },
  {
    industry: "it_tech",
    family: "cyber_security",
    canonicalTitle: "Security Architect",
    variants: ["cyber security architect"],
    seniority: "senior",
  },
  {
    industry: "it_tech",
    family: "cyber_security",
    canonicalTitle: "Application Security Engineer",
    variants: ["product security engineer", "appsec engineer"],
  },
  {
    industry: "it_tech",
    family: "cyber_security",
    canonicalTitle: "Cloud Security Engineer",
    variants: [],
  },
  {
    industry: "it_tech",
    family: "cyber_security",
    canonicalTitle: "Network Security Engineer",
    variants: [],
    tags: ["networks_telecoms"],
  },
  {
    industry: "it_tech",
    family: "cyber_security",
    canonicalTitle: "Security Operations Engineer",
    variants: ["soc engineer", "blue team engineer"],
  },
  {
    industry: "it_tech",
    family: "cyber_security",
    canonicalTitle: "SOC Analyst",
    variants: ["security operations analyst", "security operations centre analyst", "security operations center analyst"],
  },
  {
    industry: "it_tech",
    family: "cyber_security",
    canonicalTitle: "Incident Response Analyst",
    variants: ["incident response engineer"],
  },
  {
    industry: "it_tech",
    family: "cyber_security",
    canonicalTitle: "Threat Intelligence Analyst",
    variants: ["cyber threat intelligence analyst"],
  },
  {
    industry: "it_tech",
    family: "cyber_security",
    canonicalTitle: "Security Operations Center Manager",
    variants: ["security operations centre manager", "soc manager"],
    seniority: "senior",
  },
  {
    industry: "it_tech",
    family: "cyber_security",
    canonicalTitle: "Security Specialist",
    variants: ["senior security specialist", "cyber security specialist"],
  },
  {
    industry: "it_tech",
    family: "cyber_security",
    canonicalTitle: "Information Systems Security Officer",
    variants: ["isso", "information assurance manager"],
  },
  {
    industry: "it_tech",
    family: "cyber_security",
    canonicalTitle: "Penetration Tester",
    variants: ["ethical hacker", "red team engineer", "pen tester"],
  },
  // ── IT ops / IT management ───────────────────────────────────────────────
  {
    industry: "it_tech",
    family: "it_operations_service",
    canonicalTitle: "IT Manager",
    variants: ["it systems manager"],
    seniority: "senior",
  },
  {
    industry: "it_tech",
    family: "it_operations_service",
    canonicalTitle: "IT Operations Manager",
    variants: [],
    seniority: "senior",
  },
  {
    industry: "it_tech",
    family: "it_operations_service",
    canonicalTitle: "IT Service Delivery Manager",
    variants: ["it service manager"],
    seniority: "senior",
  },
  {
    industry: "it_tech",
    family: "it_operations_service",
    canonicalTitle: "IT Support Manager",
    variants: [],
    seniority: "senior",
  },
  {
    industry: "it_tech",
    family: "it_operations_service",
    canonicalTitle: "IT Infrastructure Manager",
    variants: ["infrastructure manager"],
    seniority: "senior",
  },
  {
    industry: "it_tech",
    family: "it_operations_service",
    canonicalTitle: "IT Business Partner",
    variants: ["technology business partner"],
  },
  {
    industry: "it_tech",
    family: "it_operations_service",
    canonicalTitle: "IT Coordinator",
    variants: [],
  },
  {
    industry: "it_tech",
    family: "it_operations_service",
    canonicalTitle: "IT Analyst",
    variants: [],
  },
  {
    industry: "it_tech",
    family: "it_operations_service",
    canonicalTitle: "IT Specialist",
    variants: [],
  },
  // ── Systems / infrastructure admin ───────────────────────────────────────
  {
    industry: "it_tech",
    family: "cloud_infrastructure",
    canonicalTitle: "Systems Administrator",
    variants: [
      "it systems administrator",
      "senior systems administrator",
      "server administrator",
      "sysadmin",
    ],
    tags: ["systems_network_admin"],
  },
  {
    industry: "it_tech",
    family: "cloud_infrastructure",
    canonicalTitle: "Linux Systems Administrator",
    variants: ["unix systems administrator", "linux administrator"],
    tags: ["systems_network_admin"],
  },
  {
    industry: "it_tech",
    family: "cloud_infrastructure",
    canonicalTitle: "Windows Systems Administrator",
    variants: ["windows administrator"],
    tags: ["systems_network_admin"],
  },
  {
    industry: "it_tech",
    family: "cloud_infrastructure",
    canonicalTitle: "Virtualization Engineer",
    variants: ["virtualisation engineer", "vmware engineer", "citrix engineer"],
    tags: ["systems_network_admin"],
  },
  // ── Networks / telecoms ──────────────────────────────────────────────────
  {
    industry: "it_tech",
    family: "cloud_infrastructure",
    canonicalTitle: "Network Engineer",
    variants: ["network operations engineer", "noc engineer"],
    tags: ["networks_telecoms"],
  },
  {
    industry: "it_tech",
    family: "cloud_infrastructure",
    canonicalTitle: "Senior Network Engineer",
    variants: ["lead network engineer"],
    seniority: "senior",
    tags: ["networks_telecoms"],
  },
  {
    industry: "it_tech",
    family: "cloud_infrastructure",
    canonicalTitle: "Network Architect",
    variants: [],
    seniority: "senior",
    tags: ["networks_telecoms"],
  },
  {
    industry: "it_tech",
    family: "cloud_infrastructure",
    canonicalTitle: "Network Administrator",
    variants: ["network and systems administrator"],
    tags: ["networks_telecoms", "systems_network_admin"],
  },
  {
    industry: "it_tech",
    family: "cloud_infrastructure",
    canonicalTitle: "Telecommunications Engineer",
    variants: ["telecoms engineer", "telecoms specialist", "voice engineer"],
    tags: ["networks_telecoms"],
  },
  // ── Support / helpdesk ───────────────────────────────────────────────────
  {
    industry: "it_tech",
    family: "end_user_support",
    canonicalTitle: "Service Desk Analyst",
    variants: [
      "service desk technician",
      "help desk technician",
      "help desk specialist",
      "helpdesk analyst",
      "helpdesk technician",
    ],
  },
  {
    industry: "it_tech",
    family: "end_user_support",
    canonicalTitle: "IT Support Technician",
    variants: ["it support analyst", "it support engineer"],
  },
  {
    industry: "it_tech",
    family: "end_user_support",
    canonicalTitle: "Technical Support Engineer",
    variants: ["technical support specialist", "senior support specialist"],
  },
  {
    industry: "it_tech",
    family: "end_user_support",
    canonicalTitle: "Desktop Support Engineer",
    variants: ["desktop support specialist", "desktop support technician"],
  },
  {
    industry: "it_tech",
    family: "end_user_support",
    canonicalTitle: "Field Support Engineer",
    variants: ["field service engineer"],
  },
  {
    industry: "it_tech",
    family: "end_user_support",
    canonicalTitle: "Customer Support Specialist (IT)",
    variants: ["customer support specialist it", "it customer support specialist"],
  },
  {
    industry: "it_tech",
    family: "end_user_support",
    canonicalTitle: "Application Support Analyst",
    variants: ["application support engineer", "production support engineer", "application support specialist"],
  },
  // ── Analysis / business systems ──────────────────────────────────────────
  {
    industry: "it_tech",
    family: "business_systems_analysis",
    canonicalTitle: "Systems Analyst",
    variants: ["senior systems analyst", "system analyst", "system designer"],
  },
  {
    industry: "it_tech",
    family: "business_systems_analysis",
    canonicalTitle: "Business Systems Analyst",
    variants: [],
  },
  {
    industry: "it_tech",
    family: "business_systems_analysis",
    canonicalTitle: "Technical Business Analyst",
    variants: [],
  },
  {
    industry: "it_tech",
    family: "business_systems_analysis",
    canonicalTitle: "IT Business Analyst",
    variants: ["digital business analyst"],
  },
  // ── Product management / ownership ───────────────────────────────────────
  {
    industry: "it_tech",
    family: "product_management_tech",
    canonicalTitle: "Product Manager (Technology)",
    variants: ["product manager technology", "technology product manager", "tech product manager"],
  },
  {
    industry: "it_tech",
    family: "product_management_tech",
    canonicalTitle: "Digital Product Manager",
    variants: [],
  },
  {
    industry: "it_tech",
    family: "product_management_tech",
    canonicalTitle: "Technical Product Manager",
    variants: [],
  },
  {
    industry: "it_tech",
    family: "product_management_tech",
    canonicalTitle: "Platform Product Manager",
    variants: ["api product manager"],
  },
  {
    industry: "it_tech",
    family: "product_management_tech",
    canonicalTitle: "Data Product Manager",
    variants: [],
  },
  {
    industry: "it_tech",
    family: "product_management_tech",
    canonicalTitle: "Product Owner",
    variants: ["senior product owner", "technical product owner"],
  },
  // ── Project / delivery / agile ───────────────────────────────────────────
  {
    industry: "it_tech",
    family: "project_delivery_agile",
    canonicalTitle: "IT Project Manager",
    variants: [
      "project manager it",
      "technology project manager",
      "software project manager",
      "digital project manager",
      "agile project manager",
    ],
  },
  {
    industry: "it_tech",
    family: "project_delivery_agile",
    canonicalTitle: "IT Programme Manager",
    variants: ["it program manager", "technology programme manager"],
    seniority: "senior",
  },
  {
    industry: "it_tech",
    family: "project_delivery_agile",
    canonicalTitle: "Scrum Master",
    variants: ["senior scrum master"],
  },
  {
    industry: "it_tech",
    family: "project_delivery_agile",
    canonicalTitle: "Delivery Manager",
    variants: ["agile delivery manager", "software delivery manager"],
  },
  {
    industry: "it_tech",
    family: "project_delivery_agile",
    canonicalTitle: "Release Manager",
    variants: ["software release manager"],
  },
  {
    industry: "it_tech",
    family: "project_delivery_agile",
    canonicalTitle: "Implementation Manager (Technology)",
    variants: ["implementation manager technology", "technology implementation manager", "software implementation manager"],
  },
  {
    industry: "it_tech",
    family: "project_delivery_agile",
    canonicalTitle: "Implementation Consultant (Technology)",
    variants: [
      "implementation consultant technology",
      "technology implementation consultant",
      "software implementation consultant",
      "saas implementation consultant",
      "implementation specialist technology",
    ],
  },
  // ── Design / UX / UI ─────────────────────────────────────────────────────
  {
    industry: "it_tech",
    family: "ux_design",
    canonicalTitle: "UX Designer",
    variants: ["user experience designer", "experience designer"],
  },
  {
    industry: "it_tech",
    family: "ux_design",
    canonicalTitle: "UI Designer",
    variants: ["user interface designer", "visual designer"],
  },
  {
    industry: "it_tech",
    family: "ux_design",
    canonicalTitle: "Product Designer",
    variants: [],
  },
  {
    industry: "it_tech",
    family: "ux_design",
    canonicalTitle: "Interaction Designer",
    variants: [],
  },
  {
    industry: "it_tech",
    family: "ux_design",
    canonicalTitle: "Service Designer",
    variants: [],
  },
  {
    industry: "it_tech",
    family: "ux_design",
    canonicalTitle: "UX Researcher",
    variants: ["design researcher", "user researcher"],
  },
  // ── Solutions / pre-sales / customer success ─────────────────────────────
  {
    industry: "it_tech",
    family: "solutions_presales",
    canonicalTitle: "Solution Consultant (Technology)",
    variants: ["solution consultant technology", "solutions consultant technology", "technology solution consultant"],
  },
  {
    industry: "it_tech",
    family: "solutions_presales",
    canonicalTitle: "Pre-Sales Engineer",
    variants: ["presales engineer", "pre sales consultant", "presales consultant"],
  },
  {
    industry: "it_tech",
    family: "solutions_presales",
    canonicalTitle: "Sales Engineer (Tech)",
    variants: ["sales engineer tech", "sales engineer technology"],
  },
  {
    industry: "it_tech",
    family: "solutions_presales",
    canonicalTitle: "Solutions Engineer",
    variants: [],
  },
  {
    industry: "it_tech",
    family: "solutions_presales",
    canonicalTitle: "Customer Success Engineer",
    variants: [],
  },
  {
    industry: "it_tech",
    family: "solutions_presales",
    canonicalTitle: "Implementation Engineer (SaaS)",
    variants: ["implementation engineer saas", "saas implementation engineer"],
  },
  {
    industry: "it_tech",
    family: "solutions_presales",
    canonicalTitle: "Integration Engineer",
    variants: ["api integration engineer", "systems integration engineer"],
  },
  {
    industry: "it_tech",
    family: "solutions_presales",
    canonicalTitle: "Professional Services Consultant (Tech)",
    variants: ["professional services consultant tech", "professional services consultant technology"],
  },
  // ── QA / testing ─────────────────────────────────────────────────────────
  {
    industry: "it_tech",
    family: "quality_assurance",
    canonicalTitle: "QA Engineer",
    variants: ["quality assurance engineer", "quality engineer"],
  },
  {
    industry: "it_tech",
    family: "quality_assurance",
    canonicalTitle: "QA Analyst",
    variants: ["quality assurance analyst"],
  },
  {
    industry: "it_tech",
    family: "quality_assurance",
    canonicalTitle: "Test Engineer",
    variants: ["software tester", "software test engineer"],
  },
  {
    industry: "it_tech",
    family: "quality_assurance",
    canonicalTitle: "Automation Test Engineer",
    variants: ["automation qa engineer", "test automation engineer", "sdet", "software development engineer in test"],
  },
  {
    industry: "it_tech",
    family: "quality_assurance",
    canonicalTitle: "Test Lead",
    variants: ["qa lead"],
    seniority: "senior",
  },
  {
    industry: "it_tech",
    family: "quality_assurance",
    canonicalTitle: "Test Manager",
    variants: ["qa manager"],
    seniority: "senior",
  },
  // ── Enterprise applications / CRM / ERP ──────────────────────────────────
  {
    industry: "it_tech",
    family: "business_systems_analysis",
    canonicalTitle: "Enterprise Applications Manager",
    variants: ["enterprise applications analyst"],
    tags: ["enterprise_apps_crm_erp"],
  },
  {
    industry: "it_tech",
    family: "business_systems_analysis",
    canonicalTitle: "ERP Consultant",
    variants: ["sap consultant", "oracle e-business consultant", "oracle ebs consultant"],
    tags: ["enterprise_apps_crm_erp"],
  },
  {
    industry: "it_tech",
    family: "business_systems_analysis",
    canonicalTitle: "CRM Consultant",
    variants: ["dynamics 365 consultant", "microsoft dynamics consultant"],
    tags: ["enterprise_apps_crm_erp"],
  },
  {
    industry: "it_tech",
    family: "software_engineering",
    canonicalTitle: "Salesforce Developer",
    variants: [],
    tags: ["enterprise_apps_crm_erp"],
  },
  {
    industry: "it_tech",
    family: "business_systems_analysis",
    canonicalTitle: "Salesforce Administrator",
    variants: ["salesforce admin"],
    tags: ["enterprise_apps_crm_erp"],
  },
  {
    industry: "it_tech",
    family: "software_engineering",
    canonicalTitle: "Salesforce Architect",
    variants: [],
    seniority: "senior",
    tags: ["enterprise_apps_crm_erp"],
  },
  {
    industry: "it_tech",
    family: "business_systems_analysis",
    canonicalTitle: "HR Systems Analyst (Tech)",
    variants: ["hr systems analyst tech", "hris analyst"],
    tags: ["enterprise_apps_crm_erp"],
  },
  {
    industry: "it_tech",
    family: "business_systems_analysis",
    canonicalTitle: "Finance Systems Analyst (Tech)",
    variants: ["finance systems analyst tech"],
    tags: ["enterprise_apps_crm_erp"],
  },
  // ── Training / documentation ─────────────────────────────────────────────
  {
    industry: "it_tech",
    family: "it_operations_service",
    canonicalTitle: "IT Trainer",
    variants: ["technical trainer"],
    tags: ["training_documentation"],
  },
  {
    industry: "it_tech",
    family: "it_operations_service",
    canonicalTitle: "Technical Writer",
    variants: ["technical author", "documentation specialist tech", "documentation specialist (tech)"],
    tags: ["training_documentation"],
  },
  // ── Hardware / IoT / robotics ────────────────────────────────────────────
  {
    industry: "it_tech",
    family: "software_engineering",
    canonicalTitle: "Hardware Engineer",
    variants: ["computer hardware engineer"],
    tags: ["hardware_iot_robotics"],
  },
  {
    industry: "it_tech",
    family: "software_engineering",
    canonicalTitle: "IoT Engineer",
    variants: ["iot developer", "internet of things engineer"],
    tags: ["hardware_iot_robotics"],
  },
  {
    industry: "it_tech",
    family: "software_engineering",
    canonicalTitle: "Robotics Engineer",
    variants: ["robotics software engineer"],
    tags: ["hardware_iot_robotics"],
  },
  // ── Games / interactive media ────────────────────────────────────────────
  {
    industry: "it_tech",
    family: "ux_design",
    canonicalTitle: "Game Designer",
    variants: ["level designer", "games designer"],
    tags: ["games_interactive_media"],
  },
  {
    industry: "it_tech",
    family: "software_engineering",
    canonicalTitle: "Technical Artist",
    variants: [],
    tags: ["games_interactive_media"],
  },
  // ── Innovation / R&D ─────────────────────────────────────────────────────
  {
    industry: "it_tech",
    family: "it_operations_service",
    canonicalTitle: "Digital Transformation Manager",
    variants: ["digital transformation lead"],
    tags: ["innovation_rnd_tech"],
  },
  {
    industry: "it_tech",
    family: "software_engineering",
    canonicalTitle: "Digital Solutions Architect",
    variants: [],
    seniority: "senior",
    tags: ["innovation_rnd_tech"],
  },
  {
    industry: "it_tech",
    family: "it_operations_service",
    canonicalTitle: "Innovation Manager (Technology)",
    variants: ["innovation manager technology", "technology innovation manager"],
    tags: ["innovation_rnd_tech"],
  },
  {
    industry: "it_tech",
    family: "software_engineering",
    canonicalTitle: "R&D Engineer (Tech)",
    variants: ["r&d engineer tech", "research engineer software", "research engineer (software)", "research and development engineer tech"],
    tags: ["innovation_rnd_tech"],
  },
];
