import type { CuratedTitleEntry } from "./types";

/**
 * Curated pensions job titles (full supplied list, structured).
 *
 * Same rules as insurance.ts/banking.ts: `industry` is a FinSector, `family`
 * a FinFunction; the spec's finer families (executive_leadership,
 * administration_operations, consulting_advice, actuarial_risk,
 * investment_ldi, policy_regulation_compliance,
 * member_services_communications, reporting_change_systems) live in `tags`.
 *
 * FALSE-POSITIVE RULE: titles that also exist outside pensions are only
 * included with a pensions qualifier. Most pensions titles are naturally
 * qualified ("pension"/"scheme"/"trustee"). Single-word variants only match
 * exactly.
 *
 * PASTE ADDITIONAL TITLES HERE following the same shape.
 */
export const PENSIONS_TITLES: CuratedTitleEntry[] = [
  // ── Executive leadership ─────────────────────────────────────────────────
  {
    industry: "pensions",
    family: "operations",
    canonicalTitle: "Chief Executive Officer (Pensions)",
    variants: ["pensions ceo", "chief executive officer pensions"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "pensions",
    family: "operations",
    canonicalTitle: "Chief Operating Officer (Pensions)",
    variants: ["pensions coo", "chief operating officer pensions"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "pensions",
    family: "finance",
    canonicalTitle: "Chief Financial Officer (Pensions)",
    variants: ["chief financial officer pensions", "pensions cfo"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "pensions",
    family: "investments",
    canonicalTitle: "Chief Investment Officer (Pensions)",
    variants: ["chief investment officer pensions", "pension fund cio"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "pensions",
    family: "risk",
    canonicalTitle: "Chief Risk Officer (Pensions)",
    variants: ["chief risk officer pensions", "pensions cro"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "pensions",
    family: "actuarial",
    canonicalTitle: "Chief Actuary (Pensions)",
    variants: ["chief actuary pensions", "chief pensions actuary"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "pensions",
    family: "pensions_admin",
    canonicalTitle: "Head of Pensions",
    variants: ["pensions lead"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "pensions",
    family: "pensions_admin",
    canonicalTitle: "Head of Pension Administration",
    variants: ["head of pensions administration", "pension administration manager"],
    seniority: "executive",
    tags: ["executive_leadership", "administration_operations"],
  },
  {
    industry: "pensions",
    family: "pensions_admin",
    canonicalTitle: "Head of Scheme Governance",
    variants: ["head of pension scheme governance", "scheme governance manager"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "pensions",
    family: "pensions_admin",
    canonicalTitle: "Head of Pensions Operations",
    variants: ["head of pension operations"],
    seniority: "executive",
    tags: ["executive_leadership", "administration_operations"],
  },
  {
    industry: "pensions",
    family: "pensions_admin",
    canonicalTitle: "Head of Defined Benefit Pensions",
    variants: ["head of db pensions", "head of defined benefit"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "pensions",
    family: "pensions_admin",
    canonicalTitle: "Head of Defined Contribution Pensions",
    variants: ["head of dc pensions", "head of defined contribution"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "pensions",
    family: "pensions_admin",
    canonicalTitle: "Head of Workplace Pensions",
    variants: ["workplace pensions director"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "pensions",
    family: "pensions_admin",
    canonicalTitle: "Head of Trustee Services",
    variants: ["trustee services director"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },
  {
    industry: "pensions",
    family: "client_service",
    canonicalTitle: "Head of Pensions Consulting",
    variants: ["head of pension consulting", "pensions consulting director"],
    seniority: "executive",
    tags: ["executive_leadership", "consulting_advice"],
  },
  {
    industry: "pensions",
    family: "client_service",
    canonicalTitle: "Head of Retirement Solutions",
    variants: ["retirement solutions director"],
    seniority: "executive",
    tags: ["executive_leadership"],
  },

  // ── Management & trustee services ────────────────────────────────────────
  {
    industry: "pensions",
    family: "pensions_admin",
    canonicalTitle: "Pensions Director",
    variants: ["pension director"],
    seniority: "executive",
    tags: ["administration_operations"],
  },
  {
    industry: "pensions",
    family: "pensions_admin",
    canonicalTitle: "Pensions Manager",
    variants: ["pension manager", "senior pensions manager"],
    tags: ["administration_operations"],
  },
  {
    industry: "pensions",
    family: "pensions_admin",
    canonicalTitle: "Pension Scheme Manager",
    variants: ["pensions scheme manager", "scheme manager pensions"],
    tags: ["administration_operations"],
  },
  {
    industry: "pensions",
    family: "pensions_admin",
    canonicalTitle: "Trustee Executive",
    variants: ["pension trustee executive", "professional trustee"],
    tags: ["administration_operations"],
  },
  {
    industry: "pensions",
    family: "pensions_admin",
    canonicalTitle: "Trustee Services Manager",
    variants: ["trustee services consultant"],
    tags: ["administration_operations"],
  },

  // ── Administration & operations ──────────────────────────────────────────
  {
    industry: "pensions",
    family: "pensions_admin",
    canonicalTitle: "Pensions Administrator",
    variants: ["pension administrator", "pensions admin"],
    tags: ["administration_operations"],
  },
  {
    industry: "pensions",
    family: "pensions_admin",
    canonicalTitle: "Senior Pensions Administrator",
    variants: ["senior pension administrator"],
    seniority: "senior",
    tags: ["administration_operations"],
  },
  {
    industry: "pensions",
    family: "pensions_admin",
    canonicalTitle: "Pensions Team Leader",
    variants: ["pension team leader", "pensions administration team leader"],
    tags: ["administration_operations"],
  },
  {
    industry: "pensions",
    family: "pensions_admin",
    canonicalTitle: "Pensions Operations Manager",
    variants: ["pension operations manager"],
    tags: ["administration_operations"],
  },
  {
    industry: "pensions",
    family: "pensions_admin",
    canonicalTitle: "Pension Benefit Administrator",
    variants: ["pensions benefit administrator", "benefits administrator pensions"],
    tags: ["administration_operations"],
  },
  {
    industry: "pensions",
    family: "pensions_admin",
    canonicalTitle: "Pension Payroll Administrator",
    variants: ["pensions payroll administrator", "pensioner payroll administrator"],
    tags: ["administration_operations"],
  },
  {
    industry: "pensions",
    family: "pensions_admin",
    canonicalTitle: "Pension Calculation Specialist",
    variants: ["pensions calculations specialist", "pension calculations analyst"],
    tags: ["administration_operations"],
  },
  {
    industry: "pensions",
    family: "pensions_admin",
    canonicalTitle: "Pension Data Specialist",
    variants: ["pensions data specialist", "pensions data analyst"],
    tags: ["administration_operations"],
  },
  {
    industry: "pensions",
    family: "pensions_admin",
    canonicalTitle: "Pension Transfers Specialist",
    variants: ["pensions transfer specialist", "pension transfer analyst"],
    tags: ["administration_operations"],
  },
  {
    industry: "pensions",
    family: "pensions_admin",
    canonicalTitle: "Pension Onboarding Specialist",
    variants: ["pensions onboarding specialist"],
    tags: ["administration_operations"],
  },

  // ── Consulting & advice ──────────────────────────────────────────────────
  {
    industry: "pensions",
    family: "client_service",
    canonicalTitle: "Pensions Consultant",
    variants: ["pension consultant"],
    tags: ["consulting_advice"],
  },
  {
    industry: "pensions",
    family: "client_service",
    canonicalTitle: "Senior Pensions Consultant",
    variants: ["senior pension consultant"],
    seniority: "senior",
    tags: ["consulting_advice"],
  },
  {
    industry: "pensions",
    family: "client_service",
    canonicalTitle: "Associate Pensions Consultant",
    variants: ["associate pension consultant", "trainee pensions consultant"],
    seniority: "junior",
    tags: ["consulting_advice"],
  },
  {
    industry: "pensions",
    family: "client_service",
    canonicalTitle: "Corporate Pensions Consultant",
    variants: ["corporate pension consultant"],
    tags: ["consulting_advice"],
  },
  {
    industry: "pensions",
    family: "client_service",
    canonicalTitle: "DC Pensions Consultant",
    variants: ["dc pension consultant", "defined contribution consultant"],
    tags: ["consulting_advice"],
  },
  {
    industry: "pensions",
    family: "client_service",
    canonicalTitle: "DB Pensions Consultant",
    variants: ["db pension consultant", "defined benefit consultant"],
    tags: ["consulting_advice"],
  },
  {
    industry: "pensions",
    family: "client_service",
    canonicalTitle: "Group Pensions Consultant",
    variants: ["group pension consultant"],
    tags: ["consulting_advice"],
  },
  {
    industry: "pensions",
    family: "client_service",
    canonicalTitle: "Employee Benefits Consultant (Pensions)",
    variants: ["employee benefits consultant pensions", "pensions and benefits consultant"],
    tags: ["consulting_advice"],
  },
  {
    industry: "pensions",
    family: "client_service",
    canonicalTitle: "Pension Governance Consultant",
    variants: ["pensions governance consultant", "scheme governance consultant"],
    tags: ["consulting_advice"],
  },
  {
    industry: "pensions",
    family: "client_service",
    canonicalTitle: "Pension Risk Transfer Consultant",
    variants: ["pensions risk transfer consultant", "prt consultant", "de risking consultant"],
    tags: ["consulting_advice", "de_risking"],
  },
  {
    industry: "pensions",
    family: "client_service",
    canonicalTitle: "Bulk Annuity Consultant",
    variants: ["bulk annuities consultant", "buy in buy out consultant"],
    tags: ["consulting_advice", "de_risking"],
  },

  // ── Actuarial & risk ─────────────────────────────────────────────────────
  {
    industry: "pensions",
    family: "actuarial",
    canonicalTitle: "Pensions Actuary",
    variants: ["pension actuary"],
    tags: ["actuarial_risk"],
  },
  {
    industry: "pensions",
    family: "actuarial",
    canonicalTitle: "Scheme Actuary",
    variants: ["pension scheme actuary"],
    tags: ["actuarial_risk"],
  },
  {
    industry: "pensions",
    family: "actuarial",
    canonicalTitle: "Trainee Pensions Actuary",
    variants: ["trainee pension actuary", "actuarial trainee pensions"],
    seniority: "junior",
    tags: ["actuarial_risk"],
  },
  {
    industry: "pensions",
    family: "actuarial",
    canonicalTitle: "Actuarial Analyst (Pensions)",
    variants: ["actuarial analyst pensions", "pensions actuarial analyst"],
    tags: ["actuarial_risk"],
  },
  {
    industry: "pensions",
    family: "actuarial",
    canonicalTitle: "Senior Actuarial Analyst (Pensions)",
    variants: ["senior actuarial analyst pensions", "senior pensions actuarial analyst"],
    seniority: "senior",
    tags: ["actuarial_risk"],
  },
  {
    industry: "pensions",
    family: "actuarial",
    canonicalTitle: "Pension Risk Actuary",
    variants: ["pensions risk actuary"],
    tags: ["actuarial_risk"],
  },
  {
    industry: "pensions",
    family: "actuarial",
    canonicalTitle: "De-risking Actuary",
    variants: ["de risking actuary", "buyout actuary", "pension risk transfer actuary"],
    tags: ["actuarial_risk", "de_risking"],
  },
  {
    industry: "pensions",
    family: "actuarial",
    canonicalTitle: "Longevity Risk Specialist",
    variants: ["longevity analyst", "longevity risk analyst"],
    tags: ["actuarial_risk"],
  },

  // ── Investment & LDI ─────────────────────────────────────────────────────
  {
    industry: "pensions",
    family: "investments",
    canonicalTitle: "Pension Investment Analyst",
    variants: ["pensions investment analyst", "pension fund investment analyst"],
    tags: ["investment_ldi"],
  },
  {
    industry: "pensions",
    family: "investments",
    canonicalTitle: "Pension Investment Manager",
    variants: ["pensions investment manager", "pension fund investment manager"],
    tags: ["investment_ldi"],
  },
  {
    industry: "pensions",
    family: "investments",
    canonicalTitle: "LDI Analyst",
    variants: ["liability driven investment analyst", "ldi investment analyst"],
    tags: ["investment_ldi"],
  },
  {
    industry: "pensions",
    family: "investments",
    canonicalTitle: "LDI Portfolio Manager",
    variants: ["liability driven investment portfolio manager", "ldi fund manager"],
    tags: ["investment_ldi"],
  },
  {
    industry: "pensions",
    family: "investments",
    canonicalTitle: "Asset Liability Management Analyst (Pensions)",
    variants: ["asset liability management analyst pensions", "alm analyst pensions"],
    tags: ["investment_ldi"],
  },
  {
    industry: "pensions",
    family: "investments",
    canonicalTitle: "Funding Strategy Analyst (Pensions)",
    variants: ["funding strategy analyst pensions", "pension funding analyst"],
    tags: ["investment_ldi"],
  },

  // ── Policy, regulation & compliance ──────────────────────────────────────
  {
    industry: "pensions",
    family: "compliance",
    canonicalTitle: "Pension Policy Manager",
    variants: ["pensions policy manager", "pensions policy analyst"],
    tags: ["policy_regulation_compliance"],
  },
  {
    industry: "pensions",
    family: "compliance",
    canonicalTitle: "Pension Technical Specialist",
    variants: ["pensions technical specialist", "pensions technical consultant"],
    tags: ["policy_regulation_compliance"],
  },
  {
    industry: "pensions",
    family: "compliance",
    canonicalTitle: "Pension Legislation Specialist",
    variants: ["pensions legislation specialist"],
    tags: ["policy_regulation_compliance"],
  },
  {
    industry: "pensions",
    family: "compliance",
    canonicalTitle: "Regulatory Specialist (Pensions)",
    variants: ["regulatory specialist pensions", "pensions regulatory specialist"],
    tags: ["policy_regulation_compliance"],
  },
  {
    industry: "pensions",
    family: "compliance",
    canonicalTitle: "Compliance Manager (Pensions)",
    variants: ["compliance manager pensions", "pensions compliance manager"],
    tags: ["policy_regulation_compliance"],
  },
  {
    industry: "pensions",
    family: "risk",
    canonicalTitle: "Risk Manager (Pensions)",
    variants: ["risk manager pensions", "pensions risk manager"],
    tags: ["policy_regulation_compliance"],
  },
  {
    industry: "pensions",
    family: "compliance",
    canonicalTitle: "Internal Auditor (Pensions)",
    variants: ["internal auditor pensions", "pensions internal auditor"],
    tags: ["policy_regulation_compliance"],
  },

  // ── Member services & communications ─────────────────────────────────────
  {
    industry: "pensions",
    family: "client_service",
    canonicalTitle: "Member Services Representative (Pensions)",
    variants: ["member services representative pensions", "pensions member services representative", "member services advisor pensions"],
    tags: ["member_services_communications"],
  },
  {
    industry: "pensions",
    family: "client_service",
    canonicalTitle: "Pensions Contact Centre Agent",
    variants: ["pension contact centre agent", "pensions helpline advisor"],
    tags: ["member_services_communications"],
  },
  {
    industry: "pensions",
    family: "client_service",
    canonicalTitle: "Member Communications Specialist (Pensions)",
    variants: ["member communications specialist pensions", "pensions communications specialist"],
    tags: ["member_services_communications"],
  },
  {
    industry: "pensions",
    family: "client_service",
    canonicalTitle: "Retirement Consultant",
    variants: ["retirement planning consultant"],
    tags: ["member_services_communications"],
  },
  {
    industry: "pensions",
    family: "client_service",
    canonicalTitle: "Retirement Advice Specialist",
    variants: ["retirement adviser", "retirement advisor"],
    tags: ["member_services_communications"],
  },
  {
    industry: "pensions",
    family: "client_service",
    canonicalTitle: "Retirement Options Consultant",
    variants: ["retirement options specialist"],
    tags: ["member_services_communications"],
  },

  // ── Reporting, change & systems ──────────────────────────────────────────
  {
    industry: "pensions",
    family: "pensions_admin",
    canonicalTitle: "Auto-Enrolment Specialist",
    variants: ["auto enrolment specialist", "auto enrollment specialist", "auto enrolment consultant"],
    tags: ["reporting_change_systems"],
  },
  {
    industry: "pensions",
    family: "pensions_admin",
    canonicalTitle: "Workplace Pensions Specialist",
    variants: ["workplace pension specialist", "workplace pensions consultant"],
    tags: ["reporting_change_systems"],
  },
  {
    industry: "pensions",
    family: "finance",
    canonicalTitle: "Pension Scheme Accountant",
    variants: ["pensions scheme accountant", "pension fund accountant"],
    tags: ["reporting_change_systems"],
  },
  {
    industry: "pensions",
    family: "finance",
    canonicalTitle: "Pension Reporting Accountant",
    variants: ["pensions reporting accountant"],
    tags: ["reporting_change_systems"],
  },
  {
    industry: "pensions",
    family: "operations",
    canonicalTitle: "MI Analyst (Pensions)",
    variants: ["mi analyst pensions", "pensions mi analyst", "management information analyst pensions"],
    tags: ["reporting_change_systems"],
  },
  {
    industry: "pensions",
    family: "operations",
    canonicalTitle: "Business Analyst (Pensions)",
    variants: ["business analyst pensions", "pensions business analyst"],
    tags: ["reporting_change_systems"],
  },
  {
    industry: "pensions",
    family: "operations",
    canonicalTitle: "Systems Analyst (Pensions Administration)",
    variants: ["systems analyst pensions", "pensions systems analyst", "pensions administration systems analyst"],
    tags: ["reporting_change_systems"],
  },
  {
    industry: "pensions",
    family: "operations",
    canonicalTitle: "Pensions Implementation Consultant",
    variants: ["pension implementation consultant", "pensions implementation manager"],
    tags: ["reporting_change_systems"],
  },
  {
    industry: "pensions",
    family: "operations",
    canonicalTitle: "Pensions Change Manager",
    variants: ["pension change manager", "pensions change analyst"],
    tags: ["reporting_change_systems"],
  },
];
